# Makefile Generated Wed Aug 06 14:00:02 EDT 2014
MNC=HCI
SPECFILE=HCI.spec
PCMFILE=HCI.pcm
SRC=pwrmon_conv.tmc idx64flag.tmc qcli_conv.tmc PTRH_conv.tmc
SRC+=hci_analysis cpu_usage.tmc types.tmc AIO.tmc Altimeter.tmc
SRC+=BAT_SPAN.tmc BAT_SPAN_cal.tmc Inverter.tmc T30K75KU.tmc
SRC+=T1M250KU.tmc T30K250KU.tmc T1M75KU.tmc T1M1M.tmc VigoT.tmc
SRC+=digio.tmc idx64.tmc Pilot.tmc pwrmon.tmc qcli.tmc PTRH.tmc
SRC+=hart.tmc SWData.tmc SWData.h QCLI_C.tmc QCLI_M.tmc QCLI_I.tmc
SRC+=Altimeter_col.tmc AI_col.tmc BAT_SPAN_col.tmc Inverter_col.tmc
SRC+=idx64col.tmc PTRH_col.tmc qcli_col.tmc cpu_usage_col.tmc
SRC+=SWData_col.tmc AO.cmd BAT_SPAN.cmd Inverter.cmd dccc.cmd
SRC+=qclis.cmd idx64drv.cmd subbus.cmd panel.cmd address.h SWData.cmd
SRC+=QCLI_C.cmd QCLI_M.cmd QCLI_I.cmd digio_conv.tmc P_conv.tmc
SRC+=Inverter_conv.tmc hk.tbl qcli.tbl Cells.tbl hart.tbl SSPrtg.tmc
SRC+=Calibration.tbl Pilot_conv.tmc BAT_SPAN.tbl Altimeter_conv.tmc
SRC+=hk2.tbl HCI_A.tma HCI.sws HCI_B.tma HCI_C.tma HCIeng.cdf
SRC+=CellT_raw.tmc CellT_raw.cdf HCI.doit
TOOL=HCI.spec Makefile
SCRIPT=idx64.idx64 interact dccc.dccc runfile.FF
OBJ=QCLI_C.cmd QCLI_C.out QCLI_C.tmc QCLI_C.m QCLI_C.log QCLI_M.cmd
OBJ+=QCLI_M.out QCLI_M.tmc QCLI_M.m QCLI_M.log QCLI_I.cmd QCLI_I.out
OBJ+=QCLI_I.tmc QCLI_I.m QCLI_I.log HCIcol.cc HCI.pcm tm.dac
OBJ+=HCIcoloui.c HCIcoloui.o HCIcol.o ptrhm.o ptrhm_col.o HCIcmd.cc
OBJ+=HCIcmd.dat HCIsrvr.o HCIsrvroui.c HCIsrvroui.o hktbl.tmc
OBJ+=qclitbl.tmc Cellstbl.tmc harttbl.tmc HCIdisp.cc HCIdispoui.c
OBJ+=HCIdispoui.o HCIdisp.o hktblnc.tmc qclitblnc.tmc Cellstblnc.tmc
OBJ+=harttblnc.tmc HCIdispnc.cc HCIdispncoui.c HCIdispncoui.o
OBJ+=HCIdispnc.o Calibrationtbl.tmc Caldisp.cc Caldispoui.c
OBJ+=Caldispoui.o Caldisp.o Calibrationtblnc.tmc Caldispnc.cc
OBJ+=Caldispncoui.c Caldispncoui.o Caldispnc.o BAT_SPANtbl.tmc
OBJ+=hk2tbl.tmc BSdisp.cc BSdispoui.c BSdispoui.o BSdisp.o
OBJ+=BAT_SPANtblnc.tmc hk2tblnc.tmc BSdispnc.cc BSdispncoui.c
OBJ+=BSdispncoui.o BSdispnc.o HCIsws.tma HCI_A_algoa.tmc
OBJ+=HCI_A_algo.cc HCI_A_algooui.c HCI_A_algooui.o HCI_A_algo.o
OBJ+=HCI_B_algoa.tmc HCI_B_algo.cc HCI_B_algooui.c HCI_B_algooui.o
OBJ+=HCI_B_algo.o HCI_C_algoa.tmc HCI_C_algo.cc HCI_C_algooui.c
OBJ+=HCI_C_algooui.o HCI_C_algo.o HCIengextcdf.oui HCIengext.tmc
OBJ+=HCIengext.cc HCIengextoui.c HCIengextoui.o HCIengext.o
OBJ+=HCIrawextcdf.oui CellT_rawext.tmc HCIrawext.cc HCIrawextoui.c
OBJ+=HCIrawextoui.o HCIrawext.o doit.dep HCIclt.o HCIcltoui.c
OBJ+=HCIcltoui.o HCIcltnc.o HCIcltncoui.c HCIcltncoui.o
TGT=HCIcol HCIsrvr HCIdisp HCIdispnc Caldisp Caldispnc BSdisp
TGT+=BSdispnc HCI_A_algo HCI_B_algo HCI_C_algo HCIengext HCIrawext
TGT+=doit HCIclt HCIcltnc
DISTRIB=QCLI_C.out QCLI_M.out QCLI_I.out ../BAT/BAT_SPAN
DISTRIB+=../BAT/BS2cdfext ../BAT/BSlogger ../Inverter/Inverter
DISTRIB+=../Altimeter/Altimeter HCI.pcm tm.dac
IDISTRIB=Experiment.config VERSION BSext doit
SRCDIST=QCLI_C.m QCLI_M.m QCLI_I.m HCI.sws $(qclibase)
SRCDIST+=Thermistors.txt ../BAT/N51AU.txt hk.tbl qcli.tbl Cells.tbl
SRCDIST+=hart.tbl Calibration.tbl BAT_SPAN.tbl hk2.tbl HCI_A.tma
SRCDIST+=HCI_B.tma HCI_C.tma /usr/local/share/huarp/freemem.tmc
SRCDIST+=cpu_usage.tmc /usr/local/share/huarp/vl_temp.tmc
SRCDIST+=/usr/local/share/huarp/ebx37f_temp.tmc
SRCDIST+=/usr/local/share/huarp/tmdf.tmc
SRCDIST+=/usr/local/share/huarp/ptrhm.cc
SRCDIST+=/usr/local/share/huarp/flttime.tmc types.tmc AIO.tmc
SRCDIST+=Altimeter.tmc BAT_SPAN.tmc BAT_SPAN_cal.tmc Inverter.tmc
SRCDIST+=T30K75KU.tmc T1M250KU.tmc T30K250KU.tmc T1M75KU.tmc
SRCDIST+=T1M1M.tmc VigoT.tmc digio.tmc idx64.tmc Pilot.tmc pwrmon.tmc
SRCDIST+=qcli.tmc PTRH.tmc hart.tmc SWData.tmc SWData.h QCLI_C.tmc
SRCDIST+=QCLI_M.tmc QCLI_I.tmc
TMCBASE=/usr/local/share/huarp/freemem.tmc cpu_usage.tmc
TMCBASE+=/usr/local/share/huarp/vl_temp.tmc
TMCBASE+=/usr/local/share/huarp/ebx37f_temp.tmc
TMCBASE+=/usr/local/share/huarp/tmdf.tmc
TMCBASE+=/usr/local/share/huarp/ptrhm.cc
TMCBASE+=/usr/local/share/huarp/flttime.tmc types.tmc AIO.tmc
TMCBASE+=Altimeter.tmc BAT_SPAN.tmc BAT_SPAN_cal.tmc Inverter.tmc
TMCBASE+=T30K75KU.tmc T1M250KU.tmc T30K250KU.tmc T1M75KU.tmc
TMCBASE+=T1M1M.tmc VigoT.tmc digio.tmc idx64.tmc Pilot.tmc pwrmon.tmc
TMCBASE+=qcli.tmc PTRH.tmc hart.tmc SWData.tmc SWData.h QCLI_C.tmc
TMCBASE+=QCLI_M.tmc QCLI_I.tmc
CMDBASE=/usr/local/share/huarp/root.cmd
CMDBASE+=/usr/local/share/huarp/getcon.cmd
CMDBASE+=/usr/local/share/huarp/DACS_AI.cmd
CMDBASE+=/usr/local/share/huarp/idx64.cmd
CMDBASE+=/usr/local/share/huarp/qcli.cmd
CMDBASE+=/usr/local/share/huarp/phrtg.cmd AO.cmd BAT_SPAN.cmd
CMDBASE+=Inverter.cmd dccc.cmd qclis.cmd idx64drv.cmd subbus.cmd
CMDBASE+=panel.cmd address.h SWData.cmd QCLI_C.cmd QCLI_M.cmd
CMDBASE+=QCLI_I.cmd
COLBASE=Altimeter_col.tmc AI_col.tmc BAT_SPAN_col.tmc
COLBASE+=Inverter_col.tmc idx64col.tmc PTRH_col.tmc qcli_col.tmc
COLBASE+=/usr/local/share/huarp/DACS_ID.tmc
COLBASE+=/usr/local/share/huarp/ebx37f_temp_col.tmc
COLBASE+=/usr/local/share/huarp/tmdf_col.tmc
COLBASE+=/usr/local/share/huarp/ptrhm_col.cc cpu_usage_col.tmc
COLBASE+=/usr/local/share/huarp/freemem_col.tmc SWData_col.tmc
SWSBASE=HCI.sws
QCLIBASE=QCLI_C.qcli QCLI_M.qcli QCLI_I.qcli
PHTGT=hktbl.tmc qclitbl.tmc Cellstbl.tmc harttbl.tmc
PHTGT+=Calibrationtbl.tmc BAT_SPANtbl.tmc hk2tbl.tmc
RCS=$(SRC) $(TOOL) $(SCRIPT)
SOURCE=$(RCS) $(NONRCS)
OBJECT=$(OBJ) *.err
TARGET=$(TGT)
DSTRB=$(TGT) $(DISTRIB) $(SCRIPT)
TGTDIR= $(TGTNODE)/home/hci
include /usr/local/share/huarp/appgen.mk

.PHONY : all extdistribution distribution clean check_photon

all : Makefile check_photon $(TGT) .cvsignore
Makefile : HCI.spec
	appgen HCI.spec
VERSION=`cat VERSION`
extdistribution : $(DSTRB) $(SRCDIST) VERSION
	@[ -d $(TGTDIR)/bin ] || mkdir $(TGTDIR)/bin
	@[ -d $(TGTDIR)/bin/$(VERSION) ] || mkdir $(TGTDIR)/bin/$(VERSION)
	@[ -d $(TGTDIR)/bin/$(VERSION)/Base ] || mkdir $(TGTDIR)/bin/$(VERSION)/Base
	@[ ! -f $(TGTDIR)/bin/$(VERSION)/$(PCMFILE) ] || \
	  cmp -s $(TGTDIR)/bin/$(VERSION)/$(PCMFILE) $(PCMFILE) || \
	  ( echo "$(PCMFILE) changed without VERSION update"; false )
	@distribute $(FORCE) $(TGTDIR)/bin/$(VERSION) $(DSTRB)
	@distribute $(FORCE) $(TGTDIR)/bin/$(VERSION)/Base $(SRCDIST)
distribution : extdistribution
	@distribute $(FORCE) $(TGTDIR) $(IDISTRIB)
check_photon :
ifeq ($(WPHOTON),YES)
	@for tgt in $(PHTGT); do \
	  cmp -s $$tgt /usr/local/share/huarp/nulltbl.tmc && echo Remaking $$tgt && rm -f $$tgt; \
	done; true
endif
HCIcol : HCIcol.o ptrhm.o ptrhm_col.o HCIcoloui.o
	$(LINK.privCXX) HCIcol.o ptrhm.o ptrhm_col.o HCIcoloui.o -lsubbus -ltmpp -ltm -lnort
	$(OUIUSE) HCIcoloui.c
	$(PROMOTE) HCIcol
HCIsrvr : HCIsrvr.o HCIsrvroui.o
	$(LINK.privCXX) HCIsrvr.o HCIsrvroui.o -lsubbus -ltmpp -ltm -lnort
	$(OUIUSE) HCIsrvroui.c
	$(PROMOTE) HCIsrvr
HCIdisp : HCIdisp.o ptrhm.o HCIdispoui.o
	$(LINK.normCXX) HCIdisp.o ptrhm.o HCIdispoui.o -ldisp -ltmph -lph -ltmpp -ltm -lnort
	$(OUIUSE) HCIdispoui.c
HCIdispnc : HCIdispnc.o ptrhm.o HCIdispncoui.o
	$(LINK.normCXX) HCIdispnc.o ptrhm.o HCIdispncoui.o -ldispnc -ltmnc -lncurses -ltmpp -ltm -lnort
	$(OUIUSE) HCIdispncoui.c
Caldisp : Caldisp.o ptrhm.o Caldispoui.o
	$(LINK.normCXX) Caldisp.o ptrhm.o Caldispoui.o -ldisp -ltmph -lph -ltmpp -ltm -lnort
	$(OUIUSE) Caldispoui.c
Caldispnc : Caldispnc.o ptrhm.o Caldispncoui.o
	$(LINK.normCXX) Caldispnc.o ptrhm.o Caldispncoui.o -ldispnc -ltmnc -lncurses -ltmpp -ltm -lnort
	$(OUIUSE) Caldispncoui.c
BSdisp : BSdisp.o ptrhm.o BSdispoui.o
	$(LINK.normCXX) BSdisp.o ptrhm.o BSdispoui.o -ldisp -ltmph -lph -ltmpp -ltm -lnort
	$(OUIUSE) BSdispoui.c
BSdispnc : BSdispnc.o ptrhm.o BSdispncoui.o
	$(LINK.normCXX) BSdispnc.o ptrhm.o BSdispncoui.o -ldispnc -ltmnc -lncurses -ltmpp -ltm -lnort
	$(OUIUSE) BSdispncoui.c
HCI_A_algo : HCI_A_algo.o ptrhm.o HCI_A_algooui.o
	$(LINK.normCXX) HCI_A_algo.o ptrhm.o HCI_A_algooui.o -ltmpp -ltm -lnort
	$(OUIUSE) HCI_A_algooui.c
HCI_B_algo : HCI_B_algo.o ptrhm.o HCI_B_algooui.o
	$(LINK.normCXX) HCI_B_algo.o ptrhm.o HCI_B_algooui.o -ltmpp -ltm -lnort
	$(OUIUSE) HCI_B_algooui.c
HCI_C_algo : HCI_C_algo.o ptrhm.o HCI_C_algooui.o
	$(LINK.normCXX) HCI_C_algo.o ptrhm.o HCI_C_algooui.o -ltmpp -ltm -lnort
	$(OUIUSE) HCI_C_algooui.c
HCIengext : HCIengext.o ptrhm.o HCIengextoui.o
	$(LINK.normCXX) HCIengext.o ptrhm.o HCIengextoui.o -ltmpp -ltm -lnort
	$(OUIUSE) HCIengextoui.c
HCIrawext : HCIrawext.o ptrhm.o HCIrawextoui.o
	$(LINK.normCXX) HCIrawext.o ptrhm.o HCIrawextoui.o -ltmpp -ltm -lnort
	$(OUIUSE) HCIrawextoui.c
doit : HCI.doit
	mkdoit3 -o doit  HCI.doit
HCIclt : HCIclt.o HCIcltoui.o
	$(LINK.normCXX) HCIclt.o HCIcltoui.o -ltmph -lph -ltmpp -ltm -lnort
	$(OUIUSE) HCIcltoui.c
HCIcltnc : HCIcltnc.o HCIcltncoui.o
	$(LINK.normCXX) HCIcltnc.o HCIcltncoui.o -ltmnc -lncurses -ltmpp -ltm -lnort
	$(OUIUSE) HCIcltncoui.c
HCIcol.cc : /usr/local/share/huarp/freemem.tmc cpu_usage.tmc /usr/local/share/huarp/vl_temp.tmc /usr/local/share/huarp/ebx37f_temp.tmc /usr/local/share/huarp/tmdf.tmc /usr/local/share/huarp/flttime.tmc types.tmc AIO.tmc Altimeter.tmc BAT_SPAN.tmc BAT_SPAN_cal.tmc Inverter.tmc T30K75KU.tmc T1M250KU.tmc T30K250KU.tmc T1M75KU.tmc T1M1M.tmc VigoT.tmc digio.tmc idx64.tmc Pilot.tmc pwrmon.tmc qcli.tmc PTRH.tmc hart.tmc SWData.tmc QCLI_C.tmc QCLI_M.tmc QCLI_I.tmc Altimeter_col.tmc AI_col.tmc BAT_SPAN_col.tmc Inverter_col.tmc idx64col.tmc PTRH_col.tmc qcli_col.tmc /usr/local/share/huarp/DACS_ID.tmc /usr/local/share/huarp/ebx37f_temp_col.tmc /usr/local/share/huarp/tmdf_col.tmc cpu_usage_col.tmc /usr/local/share/huarp/freemem_col.tmc SWData_col.tmc
	$(TMC.col) /usr/local/share/huarp/freemem.tmc cpu_usage.tmc /usr/local/share/huarp/vl_temp.tmc /usr/local/share/huarp/ebx37f_temp.tmc /usr/local/share/huarp/tmdf.tmc /usr/local/share/huarp/flttime.tmc types.tmc AIO.tmc Altimeter.tmc BAT_SPAN.tmc BAT_SPAN_cal.tmc Inverter.tmc T30K75KU.tmc T1M250KU.tmc T30K250KU.tmc T1M75KU.tmc T1M1M.tmc VigoT.tmc digio.tmc idx64.tmc Pilot.tmc pwrmon.tmc qcli.tmc PTRH.tmc hart.tmc SWData.tmc QCLI_C.tmc QCLI_M.tmc QCLI_I.tmc Altimeter_col.tmc AI_col.tmc BAT_SPAN_col.tmc Inverter_col.tmc idx64col.tmc PTRH_col.tmc qcli_col.tmc /usr/local/share/huarp/DACS_ID.tmc /usr/local/share/huarp/ebx37f_temp_col.tmc /usr/local/share/huarp/tmdf_col.tmc cpu_usage_col.tmc /usr/local/share/huarp/freemem_col.tmc SWData_col.tmc
HCIcoloui.c : $(OUIDIR)/collect.oui $(OUIDIR)/seteuid.oui $(OUIDIR)/subbus.oui $(OUIDIR)/msg.oui
	$(OUI) $(OUIDIR)/collect.oui $(OUIDIR)/seteuid.oui $(OUIDIR)/subbus.oui $(OUIDIR)/msg.oui
HCIcoloui.o : HCIcoloui.c SWData.h
HCIcol.o : HCIcol.cc SWData.h
ptrhm.o : /usr/local/share/huarp/ptrhm.cc SWData.h
	$(COMPILE.cc) /usr/local/share/huarp/ptrhm.cc
ptrhm_col.o : /usr/local/share/huarp/ptrhm_col.cc SWData.h
	$(COMPILE.cc) /usr/local/share/huarp/ptrhm_col.cc
HCIcmd.cc : /usr/local/share/huarp/root.cmd /usr/local/share/huarp/getcon.cmd /usr/local/share/huarp/DACS_AI.cmd /usr/local/share/huarp/idx64.cmd /usr/local/share/huarp/qcli.cmd /usr/local/share/huarp/phrtg.cmd AO.cmd BAT_SPAN.cmd Inverter.cmd dccc.cmd qclis.cmd idx64drv.cmd subbus.cmd panel.cmd SWData.cmd QCLI_C.cmd QCLI_M.cmd QCLI_I.cmd
	$(CMDGEN) -d HCIcmd.dat /usr/local/share/huarp/root.cmd /usr/local/share/huarp/getcon.cmd /usr/local/share/huarp/DACS_AI.cmd /usr/local/share/huarp/idx64.cmd /usr/local/share/huarp/qcli.cmd /usr/local/share/huarp/phrtg.cmd AO.cmd BAT_SPAN.cmd Inverter.cmd dccc.cmd qclis.cmd idx64drv.cmd subbus.cmd panel.cmd SWData.cmd QCLI_C.cmd QCLI_M.cmd QCLI_I.cmd
HCIsrvr.o : HCIcmd.cc
	$(COMPILE.srvr) HCIcmd.cc
HCIsrvroui.c : $(OUIDIR)/cis.oui $(OUIDIR)/seteuid.oui $(OUIDIR)/subbus.oui $(OUIDIR)/msg.oui
	$(OUI) $(OUIDIR)/cis.oui $(OUIDIR)/seteuid.oui $(OUIDIR)/subbus.oui $(OUIDIR)/msg.oui
HCIsrvroui.o : HCIsrvroui.c address.h
hktbl.tmc : hk.tbl
qclitbl.tmc : qcli.tbl
Cellstbl.tmc : Cells.tbl
harttbl.tmc : hart.tbl
HCIdisp.cc : /usr/local/share/huarp/freemem.tmc cpu_usage.tmc /usr/local/share/huarp/vl_temp.tmc /usr/local/share/huarp/ebx37f_temp.tmc /usr/local/share/huarp/tmdf.tmc /usr/local/share/huarp/flttime.tmc types.tmc AIO.tmc Altimeter.tmc BAT_SPAN.tmc BAT_SPAN_cal.tmc Inverter.tmc T30K75KU.tmc T1M250KU.tmc T30K250KU.tmc T1M75KU.tmc T1M1M.tmc VigoT.tmc digio.tmc idx64.tmc Pilot.tmc pwrmon.tmc qcli.tmc PTRH.tmc hart.tmc SWData.tmc QCLI_C.tmc QCLI_M.tmc QCLI_I.tmc PTRH_conv.tmc pwrmon_conv.tmc digio_conv.tmc idx64flag.tmc qcli_conv.tmc P_conv.tmc Inverter_conv.tmc hktbl.tmc qclitbl.tmc Cellstbl.tmc harttbl.tmc SSPrtg.tmc
	$(TMC) /usr/local/share/huarp/freemem.tmc cpu_usage.tmc /usr/local/share/huarp/vl_temp.tmc /usr/local/share/huarp/ebx37f_temp.tmc /usr/local/share/huarp/tmdf.tmc /usr/local/share/huarp/flttime.tmc types.tmc AIO.tmc Altimeter.tmc BAT_SPAN.tmc BAT_SPAN_cal.tmc Inverter.tmc T30K75KU.tmc T1M250KU.tmc T30K250KU.tmc T1M75KU.tmc T1M1M.tmc VigoT.tmc digio.tmc idx64.tmc Pilot.tmc pwrmon.tmc qcli.tmc PTRH.tmc hart.tmc SWData.tmc QCLI_C.tmc QCLI_M.tmc QCLI_I.tmc PTRH_conv.tmc pwrmon_conv.tmc digio_conv.tmc idx64flag.tmc qcli_conv.tmc P_conv.tmc Inverter_conv.tmc hktbl.tmc qclitbl.tmc Cellstbl.tmc harttbl.tmc SSPrtg.tmc
HCIdispoui.c : /usr/local/share/oui/cic.oui $(OUIDIR)/dc.oui $(OUIDIR)/msg.oui
	$(OUI) /usr/local/share/oui/cic.oui $(OUIDIR)/dc.oui $(OUIDIR)/msg.oui
HCIdispoui.o : HCIdispoui.c SWData.h
HCIdisp.o : HCIdisp.cc SWData.h
hktblnc.tmc : hk.tbl
qclitblnc.tmc : qcli.tbl
Cellstblnc.tmc : Cells.tbl
harttblnc.tmc : hart.tbl
HCIdispnc.cc : /usr/local/share/huarp/freemem.tmc cpu_usage.tmc /usr/local/share/huarp/vl_temp.tmc /usr/local/share/huarp/ebx37f_temp.tmc /usr/local/share/huarp/tmdf.tmc /usr/local/share/huarp/flttime.tmc types.tmc AIO.tmc Altimeter.tmc BAT_SPAN.tmc BAT_SPAN_cal.tmc Inverter.tmc T30K75KU.tmc T1M250KU.tmc T30K250KU.tmc T1M75KU.tmc T1M1M.tmc VigoT.tmc digio.tmc idx64.tmc Pilot.tmc pwrmon.tmc qcli.tmc PTRH.tmc hart.tmc SWData.tmc QCLI_C.tmc QCLI_M.tmc QCLI_I.tmc PTRH_conv.tmc pwrmon_conv.tmc digio_conv.tmc idx64flag.tmc qcli_conv.tmc P_conv.tmc Inverter_conv.tmc hktblnc.tmc qclitblnc.tmc Cellstblnc.tmc harttblnc.tmc SSPrtg.tmc
	$(TMC) /usr/local/share/huarp/freemem.tmc cpu_usage.tmc /usr/local/share/huarp/vl_temp.tmc /usr/local/share/huarp/ebx37f_temp.tmc /usr/local/share/huarp/tmdf.tmc /usr/local/share/huarp/flttime.tmc types.tmc AIO.tmc Altimeter.tmc BAT_SPAN.tmc BAT_SPAN_cal.tmc Inverter.tmc T30K75KU.tmc T1M250KU.tmc T30K250KU.tmc T1M75KU.tmc T1M1M.tmc VigoT.tmc digio.tmc idx64.tmc Pilot.tmc pwrmon.tmc qcli.tmc PTRH.tmc hart.tmc SWData.tmc QCLI_C.tmc QCLI_M.tmc QCLI_I.tmc PTRH_conv.tmc pwrmon_conv.tmc digio_conv.tmc idx64flag.tmc qcli_conv.tmc P_conv.tmc Inverter_conv.tmc hktblnc.tmc qclitblnc.tmc Cellstblnc.tmc harttblnc.tmc SSPrtg.tmc
HCIdispncoui.c : /usr/local/share/oui/cic.oui $(OUIDIR)/nctable.oui $(OUIDIR)/dc.oui $(OUIDIR)/msg.oui
	$(OUI) /usr/local/share/oui/cic.oui $(OUIDIR)/nctable.oui $(OUIDIR)/dc.oui $(OUIDIR)/msg.oui
HCIdispncoui.o : HCIdispncoui.c SWData.h
HCIdispnc.o : HCIdispnc.cc SWData.h
Calibrationtbl.tmc : Calibration.tbl
Caldisp.cc : /usr/local/share/huarp/freemem.tmc cpu_usage.tmc /usr/local/share/huarp/vl_temp.tmc /usr/local/share/huarp/ebx37f_temp.tmc /usr/local/share/huarp/tmdf.tmc /usr/local/share/huarp/flttime.tmc types.tmc AIO.tmc Altimeter.tmc BAT_SPAN.tmc BAT_SPAN_cal.tmc Inverter.tmc T30K75KU.tmc T1M250KU.tmc T30K250KU.tmc T1M75KU.tmc T1M1M.tmc VigoT.tmc digio.tmc idx64.tmc Pilot.tmc pwrmon.tmc qcli.tmc PTRH.tmc hart.tmc SWData.tmc QCLI_C.tmc QCLI_M.tmc QCLI_I.tmc digio_conv.tmc Calibrationtbl.tmc
	$(TMC) /usr/local/share/huarp/freemem.tmc cpu_usage.tmc /usr/local/share/huarp/vl_temp.tmc /usr/local/share/huarp/ebx37f_temp.tmc /usr/local/share/huarp/tmdf.tmc /usr/local/share/huarp/flttime.tmc types.tmc AIO.tmc Altimeter.tmc BAT_SPAN.tmc BAT_SPAN_cal.tmc Inverter.tmc T30K75KU.tmc T1M250KU.tmc T30K250KU.tmc T1M75KU.tmc T1M1M.tmc VigoT.tmc digio.tmc idx64.tmc Pilot.tmc pwrmon.tmc qcli.tmc PTRH.tmc hart.tmc SWData.tmc QCLI_C.tmc QCLI_M.tmc QCLI_I.tmc digio_conv.tmc Calibrationtbl.tmc
Caldispoui.c : $(OUIDIR)/dc.oui $(OUIDIR)/msg.oui
	$(OUI) $(OUIDIR)/dc.oui $(OUIDIR)/msg.oui
Caldispoui.o : Caldispoui.c SWData.h
Caldisp.o : Caldisp.cc SWData.h
Calibrationtblnc.tmc : Calibration.tbl
Caldispnc.cc : /usr/local/share/huarp/freemem.tmc cpu_usage.tmc /usr/local/share/huarp/vl_temp.tmc /usr/local/share/huarp/ebx37f_temp.tmc /usr/local/share/huarp/tmdf.tmc /usr/local/share/huarp/flttime.tmc types.tmc AIO.tmc Altimeter.tmc BAT_SPAN.tmc BAT_SPAN_cal.tmc Inverter.tmc T30K75KU.tmc T1M250KU.tmc T30K250KU.tmc T1M75KU.tmc T1M1M.tmc VigoT.tmc digio.tmc idx64.tmc Pilot.tmc pwrmon.tmc qcli.tmc PTRH.tmc hart.tmc SWData.tmc QCLI_C.tmc QCLI_M.tmc QCLI_I.tmc digio_conv.tmc Calibrationtblnc.tmc
	$(TMC) /usr/local/share/huarp/freemem.tmc cpu_usage.tmc /usr/local/share/huarp/vl_temp.tmc /usr/local/share/huarp/ebx37f_temp.tmc /usr/local/share/huarp/tmdf.tmc /usr/local/share/huarp/flttime.tmc types.tmc AIO.tmc Altimeter.tmc BAT_SPAN.tmc BAT_SPAN_cal.tmc Inverter.tmc T30K75KU.tmc T1M250KU.tmc T30K250KU.tmc T1M75KU.tmc T1M1M.tmc VigoT.tmc digio.tmc idx64.tmc Pilot.tmc pwrmon.tmc qcli.tmc PTRH.tmc hart.tmc SWData.tmc QCLI_C.tmc QCLI_M.tmc QCLI_I.tmc digio_conv.tmc Calibrationtblnc.tmc
Caldispncoui.c : $(OUIDIR)/nctable.oui $(OUIDIR)/dc.oui $(OUIDIR)/msg.oui
	$(OUI) $(OUIDIR)/nctable.oui $(OUIDIR)/dc.oui $(OUIDIR)/msg.oui
Caldispncoui.o : Caldispncoui.c SWData.h
Caldispnc.o : Caldispnc.cc SWData.h
BAT_SPANtbl.tmc : BAT_SPAN.tbl
hk2tbl.tmc : hk2.tbl
BSdisp.cc : /usr/local/share/huarp/freemem.tmc cpu_usage.tmc /usr/local/share/huarp/vl_temp.tmc /usr/local/share/huarp/ebx37f_temp.tmc /usr/local/share/huarp/tmdf.tmc /usr/local/share/huarp/flttime.tmc types.tmc AIO.tmc Altimeter.tmc BAT_SPAN.tmc BAT_SPAN_cal.tmc Inverter.tmc T30K75KU.tmc T1M250KU.tmc T30K250KU.tmc T1M75KU.tmc T1M1M.tmc VigoT.tmc digio.tmc idx64.tmc Pilot.tmc pwrmon.tmc qcli.tmc PTRH.tmc hart.tmc SWData.tmc QCLI_C.tmc QCLI_M.tmc QCLI_I.tmc Pilot_conv.tmc digio_conv.tmc qcli_conv.tmc Inverter_conv.tmc BAT_SPANtbl.tmc Altimeter_conv.tmc hk2tbl.tmc
	$(TMC) /usr/local/share/huarp/freemem.tmc cpu_usage.tmc /usr/local/share/huarp/vl_temp.tmc /usr/local/share/huarp/ebx37f_temp.tmc /usr/local/share/huarp/tmdf.tmc /usr/local/share/huarp/flttime.tmc types.tmc AIO.tmc Altimeter.tmc BAT_SPAN.tmc BAT_SPAN_cal.tmc Inverter.tmc T30K75KU.tmc T1M250KU.tmc T30K250KU.tmc T1M75KU.tmc T1M1M.tmc VigoT.tmc digio.tmc idx64.tmc Pilot.tmc pwrmon.tmc qcli.tmc PTRH.tmc hart.tmc SWData.tmc QCLI_C.tmc QCLI_M.tmc QCLI_I.tmc Pilot_conv.tmc digio_conv.tmc qcli_conv.tmc Inverter_conv.tmc BAT_SPANtbl.tmc Altimeter_conv.tmc hk2tbl.tmc
BSdispoui.c : $(OUIDIR)/dc.oui $(OUIDIR)/msg.oui
	$(OUI) $(OUIDIR)/dc.oui $(OUIDIR)/msg.oui
BSdispoui.o : BSdispoui.c SWData.h
BSdisp.o : BSdisp.cc SWData.h
BAT_SPANtblnc.tmc : BAT_SPAN.tbl
hk2tblnc.tmc : hk2.tbl
BSdispnc.cc : /usr/local/share/huarp/freemem.tmc cpu_usage.tmc /usr/local/share/huarp/vl_temp.tmc /usr/local/share/huarp/ebx37f_temp.tmc /usr/local/share/huarp/tmdf.tmc /usr/local/share/huarp/flttime.tmc types.tmc AIO.tmc Altimeter.tmc BAT_SPAN.tmc BAT_SPAN_cal.tmc Inverter.tmc T30K75KU.tmc T1M250KU.tmc T30K250KU.tmc T1M75KU.tmc T1M1M.tmc VigoT.tmc digio.tmc idx64.tmc Pilot.tmc pwrmon.tmc qcli.tmc PTRH.tmc hart.tmc SWData.tmc QCLI_C.tmc QCLI_M.tmc QCLI_I.tmc Pilot_conv.tmc digio_conv.tmc qcli_conv.tmc Inverter_conv.tmc BAT_SPANtblnc.tmc Altimeter_conv.tmc hk2tblnc.tmc
	$(TMC) /usr/local/share/huarp/freemem.tmc cpu_usage.tmc /usr/local/share/huarp/vl_temp.tmc /usr/local/share/huarp/ebx37f_temp.tmc /usr/local/share/huarp/tmdf.tmc /usr/local/share/huarp/flttime.tmc types.tmc AIO.tmc Altimeter.tmc BAT_SPAN.tmc BAT_SPAN_cal.tmc Inverter.tmc T30K75KU.tmc T1M250KU.tmc T30K250KU.tmc T1M75KU.tmc T1M1M.tmc VigoT.tmc digio.tmc idx64.tmc Pilot.tmc pwrmon.tmc qcli.tmc PTRH.tmc hart.tmc SWData.tmc QCLI_C.tmc QCLI_M.tmc QCLI_I.tmc Pilot_conv.tmc digio_conv.tmc qcli_conv.tmc Inverter_conv.tmc BAT_SPANtblnc.tmc Altimeter_conv.tmc hk2tblnc.tmc
BSdispncoui.c : $(OUIDIR)/nctable.oui $(OUIDIR)/dc.oui $(OUIDIR)/msg.oui
	$(OUI) $(OUIDIR)/nctable.oui $(OUIDIR)/dc.oui $(OUIDIR)/msg.oui
BSdispncoui.o : BSdispncoui.c SWData.h
BSdispnc.o : BSdispnc.cc SWData.h
HCIsws.tma : HCI.sws
	$(COMPILE.sws) HCI.sws
HCI_A_algoa.tmc : HCI_A.tma HCIsws.tma HCIsrvr
	$(SERVER) ./HCIsrvr
	$(TMCALGO) -V "`./HCIsrvr -R`" HCI_A.tma HCIsws.tma
HCI_A_algo.cc : /usr/local/share/huarp/freemem.tmc cpu_usage.tmc /usr/local/share/huarp/vl_temp.tmc /usr/local/share/huarp/ebx37f_temp.tmc /usr/local/share/huarp/tmdf.tmc /usr/local/share/huarp/flttime.tmc types.tmc AIO.tmc Altimeter.tmc BAT_SPAN.tmc BAT_SPAN_cal.tmc Inverter.tmc T30K75KU.tmc T1M250KU.tmc T30K250KU.tmc T1M75KU.tmc T1M1M.tmc VigoT.tmc digio.tmc idx64.tmc Pilot.tmc pwrmon.tmc qcli.tmc PTRH.tmc hart.tmc SWData.tmc QCLI_C.tmc QCLI_M.tmc QCLI_I.tmc P_conv.tmc qcli_conv.tmc digio_conv.tmc Inverter_conv.tmc Pilot_conv.tmc HCI_A_algoa.tmc
	$(TMC) /usr/local/share/huarp/freemem.tmc cpu_usage.tmc /usr/local/share/huarp/vl_temp.tmc /usr/local/share/huarp/ebx37f_temp.tmc /usr/local/share/huarp/tmdf.tmc /usr/local/share/huarp/flttime.tmc types.tmc AIO.tmc Altimeter.tmc BAT_SPAN.tmc BAT_SPAN_cal.tmc Inverter.tmc T30K75KU.tmc T1M250KU.tmc T30K250KU.tmc T1M75KU.tmc T1M1M.tmc VigoT.tmc digio.tmc idx64.tmc Pilot.tmc pwrmon.tmc qcli.tmc PTRH.tmc hart.tmc SWData.tmc QCLI_C.tmc QCLI_M.tmc QCLI_I.tmc P_conv.tmc qcli_conv.tmc digio_conv.tmc Inverter_conv.tmc Pilot_conv.tmc HCI_A_algoa.tmc
HCI_A_algooui.c : $(OUIDIR)/tma.oui $(OUIDIR)/dc.oui $(OUIDIR)/msg.oui
	$(OUI) $(OUIDIR)/tma.oui $(OUIDIR)/dc.oui $(OUIDIR)/msg.oui
HCI_A_algooui.o : HCI_A_algooui.c SWData.h
HCI_A_algo.o : HCI_A_algo.cc SWData.h
HCI_B_algoa.tmc : HCI_B.tma HCIsws.tma HCIsrvr
	$(SERVER) ./HCIsrvr
	$(TMCALGO) -V "`./HCIsrvr -R`" HCI_B.tma HCIsws.tma
HCI_B_algo.cc : /usr/local/share/huarp/freemem.tmc cpu_usage.tmc /usr/local/share/huarp/vl_temp.tmc /usr/local/share/huarp/ebx37f_temp.tmc /usr/local/share/huarp/tmdf.tmc /usr/local/share/huarp/flttime.tmc types.tmc AIO.tmc Altimeter.tmc BAT_SPAN.tmc BAT_SPAN_cal.tmc Inverter.tmc T30K75KU.tmc T1M250KU.tmc T30K250KU.tmc T1M75KU.tmc T1M1M.tmc VigoT.tmc digio.tmc idx64.tmc Pilot.tmc pwrmon.tmc qcli.tmc PTRH.tmc hart.tmc SWData.tmc QCLI_C.tmc QCLI_M.tmc QCLI_I.tmc P_conv.tmc qcli_conv.tmc digio_conv.tmc Inverter_conv.tmc Pilot_conv.tmc HCI_B_algoa.tmc
	$(TMC) /usr/local/share/huarp/freemem.tmc cpu_usage.tmc /usr/local/share/huarp/vl_temp.tmc /usr/local/share/huarp/ebx37f_temp.tmc /usr/local/share/huarp/tmdf.tmc /usr/local/share/huarp/flttime.tmc types.tmc AIO.tmc Altimeter.tmc BAT_SPAN.tmc BAT_SPAN_cal.tmc Inverter.tmc T30K75KU.tmc T1M250KU.tmc T30K250KU.tmc T1M75KU.tmc T1M1M.tmc VigoT.tmc digio.tmc idx64.tmc Pilot.tmc pwrmon.tmc qcli.tmc PTRH.tmc hart.tmc SWData.tmc QCLI_C.tmc QCLI_M.tmc QCLI_I.tmc P_conv.tmc qcli_conv.tmc digio_conv.tmc Inverter_conv.tmc Pilot_conv.tmc HCI_B_algoa.tmc
HCI_B_algooui.c : $(OUIDIR)/tma.oui $(OUIDIR)/dc.oui $(OUIDIR)/msg.oui
	$(OUI) $(OUIDIR)/tma.oui $(OUIDIR)/dc.oui $(OUIDIR)/msg.oui
HCI_B_algooui.o : HCI_B_algooui.c SWData.h
HCI_B_algo.o : HCI_B_algo.cc SWData.h
HCI_C_algoa.tmc : HCI_C.tma HCIsws.tma HCIsrvr
	$(SERVER) ./HCIsrvr
	$(TMCALGO) -V "`./HCIsrvr -R`" HCI_C.tma HCIsws.tma
HCI_C_algo.cc : /usr/local/share/huarp/freemem.tmc cpu_usage.tmc /usr/local/share/huarp/vl_temp.tmc /usr/local/share/huarp/ebx37f_temp.tmc /usr/local/share/huarp/tmdf.tmc /usr/local/share/huarp/flttime.tmc types.tmc AIO.tmc Altimeter.tmc BAT_SPAN.tmc BAT_SPAN_cal.tmc Inverter.tmc T30K75KU.tmc T1M250KU.tmc T30K250KU.tmc T1M75KU.tmc T1M1M.tmc VigoT.tmc digio.tmc idx64.tmc Pilot.tmc pwrmon.tmc qcli.tmc PTRH.tmc hart.tmc SWData.tmc QCLI_C.tmc QCLI_M.tmc QCLI_I.tmc P_conv.tmc qcli_conv.tmc digio_conv.tmc Inverter_conv.tmc Pilot_conv.tmc HCI_C_algoa.tmc
	$(TMC) /usr/local/share/huarp/freemem.tmc cpu_usage.tmc /usr/local/share/huarp/vl_temp.tmc /usr/local/share/huarp/ebx37f_temp.tmc /usr/local/share/huarp/tmdf.tmc /usr/local/share/huarp/flttime.tmc types.tmc AIO.tmc Altimeter.tmc BAT_SPAN.tmc BAT_SPAN_cal.tmc Inverter.tmc T30K75KU.tmc T1M250KU.tmc T30K250KU.tmc T1M75KU.tmc T1M1M.tmc VigoT.tmc digio.tmc idx64.tmc Pilot.tmc pwrmon.tmc qcli.tmc PTRH.tmc hart.tmc SWData.tmc QCLI_C.tmc QCLI_M.tmc QCLI_I.tmc P_conv.tmc qcli_conv.tmc digio_conv.tmc Inverter_conv.tmc Pilot_conv.tmc HCI_C_algoa.tmc
HCI_C_algooui.c : $(OUIDIR)/tma.oui $(OUIDIR)/dc.oui $(OUIDIR)/msg.oui
	$(OUI) $(OUIDIR)/tma.oui $(OUIDIR)/dc.oui $(OUIDIR)/msg.oui
HCI_C_algooui.o : HCI_C_algooui.c SWData.h
HCI_C_algo.o : HCI_C_algo.cc SWData.h
HCIengextcdf.oui : HCIeng.cdf
	$(EDF2OUI) HCIeng.cdf
HCIengext.tmc : HCIeng.cdf
	$(EDF2EXT) HCIeng.cdf
HCIengext.cc : /usr/local/share/huarp/freemem.tmc cpu_usage.tmc /usr/local/share/huarp/vl_temp.tmc /usr/local/share/huarp/ebx37f_temp.tmc /usr/local/share/huarp/tmdf.tmc /usr/local/share/huarp/flttime.tmc types.tmc AIO.tmc Altimeter.tmc BAT_SPAN.tmc BAT_SPAN_cal.tmc Inverter.tmc T30K75KU.tmc T1M250KU.tmc T30K250KU.tmc T1M75KU.tmc T1M1M.tmc VigoT.tmc digio.tmc idx64.tmc Pilot.tmc pwrmon.tmc qcli.tmc PTRH.tmc hart.tmc SWData.tmc QCLI_C.tmc QCLI_M.tmc QCLI_I.tmc qcli_conv.tmc PTRH_conv.tmc P_conv.tmc Altimeter_conv.tmc HCIengext.tmc
	$(TMC) /usr/local/share/huarp/freemem.tmc cpu_usage.tmc /usr/local/share/huarp/vl_temp.tmc /usr/local/share/huarp/ebx37f_temp.tmc /usr/local/share/huarp/tmdf.tmc /usr/local/share/huarp/flttime.tmc types.tmc AIO.tmc Altimeter.tmc BAT_SPAN.tmc BAT_SPAN_cal.tmc Inverter.tmc T30K75KU.tmc T1M250KU.tmc T30K250KU.tmc T1M75KU.tmc T1M1M.tmc VigoT.tmc digio.tmc idx64.tmc Pilot.tmc pwrmon.tmc qcli.tmc PTRH.tmc hart.tmc SWData.tmc QCLI_C.tmc QCLI_M.tmc QCLI_I.tmc qcli_conv.tmc PTRH_conv.tmc P_conv.tmc Altimeter_conv.tmc HCIengext.tmc
HCIengextoui.c : HCIengextcdf.oui $(OUIDIR)/dc.oui $(OUIDIR)/msg.oui
	$(OUI) HCIengextcdf.oui $(OUIDIR)/dc.oui $(OUIDIR)/msg.oui
HCIengextoui.o : HCIengextoui.c SWData.h
HCIengext.o : HCIengext.cc SWData.h
HCIrawextcdf.oui : CellT_raw.cdf
	$(EDF2OUI) CellT_raw.cdf
CellT_rawext.tmc : CellT_raw.cdf
	$(EDF2EXT) CellT_raw.cdf
HCIrawext.cc : /usr/local/share/huarp/freemem.tmc cpu_usage.tmc /usr/local/share/huarp/vl_temp.tmc /usr/local/share/huarp/ebx37f_temp.tmc /usr/local/share/huarp/tmdf.tmc /usr/local/share/huarp/flttime.tmc types.tmc AIO.tmc Altimeter.tmc BAT_SPAN.tmc BAT_SPAN_cal.tmc Inverter.tmc T30K75KU.tmc T1M250KU.tmc T30K250KU.tmc T1M75KU.tmc T1M1M.tmc VigoT.tmc digio.tmc idx64.tmc Pilot.tmc pwrmon.tmc qcli.tmc PTRH.tmc hart.tmc SWData.tmc QCLI_C.tmc QCLI_M.tmc QCLI_I.tmc CellT_raw.tmc CellT_rawext.tmc
	$(TMC) /usr/local/share/huarp/freemem.tmc cpu_usage.tmc /usr/local/share/huarp/vl_temp.tmc /usr/local/share/huarp/ebx37f_temp.tmc /usr/local/share/huarp/tmdf.tmc /usr/local/share/huarp/flttime.tmc types.tmc AIO.tmc Altimeter.tmc BAT_SPAN.tmc BAT_SPAN_cal.tmc Inverter.tmc T30K75KU.tmc T1M250KU.tmc T30K250KU.tmc T1M75KU.tmc T1M1M.tmc VigoT.tmc digio.tmc idx64.tmc Pilot.tmc pwrmon.tmc qcli.tmc PTRH.tmc hart.tmc SWData.tmc QCLI_C.tmc QCLI_M.tmc QCLI_I.tmc CellT_raw.tmc CellT_rawext.tmc
HCIrawextoui.c : HCIrawextcdf.oui $(OUIDIR)/dc.oui $(OUIDIR)/msg.oui
	$(OUI) HCIrawextcdf.oui $(OUIDIR)/dc.oui $(OUIDIR)/msg.oui
HCIrawextoui.o : HCIrawextoui.c SWData.h
HCIrawext.o : HCIrawext.cc SWData.h
doit.dep : HCI.doit
	mkdoit3 -M -o doit  HCI.doit
-include doit.dep
HCIclt.o : HCIcmd.cc
	$(COMPILE.clt) HCIcmd.cc
HCIcltoui.c : $(OUIDIR)/kbdclt.oui $(OUIDIR)/msg.oui
	$(OUI) $(OUIDIR)/kbdclt.oui $(OUIDIR)/msg.oui
HCIcltoui.o : HCIcltoui.c address.h
HCIcltnc.o : HCIcmd.cc
	$(COMPILE.cltnc) HCIcmd.cc
HCIcltncoui.c : $(OUIDIR)/kbdclt.oui $(OUIDIR)/nctable.oui $(OUIDIR)/msg.oui
	$(OUI) $(OUIDIR)/kbdclt.oui $(OUIDIR)/nctable.oui $(OUIDIR)/msg.oui
HCIcltncoui.o : HCIcltncoui.c address.h
SWData.h SWData.tmc SWData_col.tmc SWData.cmd :  HCI.sws
	swscomp -o SWData  HCI.sws
QCLI_C.cmd QCLI_C.out QCLI_C.tmc QCLI_C.m : QCLI_C.qcli
	qclicomp -o QCLI_C.out -c QCLI_C.cmd -d QCLI_C.tmc \
	  -v QCLI_C.log -m QCLI_C.m QCLI_C.qcli || \
	  ( rm -f QCLI_C.out QCLI_C.cmd QCLI_C.tmc QCLI_C.log QCLI_C.m; false )
QCLI_M.cmd QCLI_M.out QCLI_M.tmc QCLI_M.m : QCLI_M.qcli
	qclicomp -o QCLI_M.out -c QCLI_M.cmd -d QCLI_M.tmc \
	  -v QCLI_M.log -m QCLI_M.m QCLI_M.qcli || \
	  ( rm -f QCLI_M.out QCLI_M.cmd QCLI_M.tmc QCLI_M.log QCLI_M.m; false )
QCLI_I.cmd QCLI_I.out QCLI_I.tmc QCLI_I.m : QCLI_I.qcli
	qclicomp -o QCLI_I.out -c QCLI_I.cmd -d QCLI_I.tmc \
	  -v QCLI_I.log -m QCLI_I.m QCLI_I.qcli || \
	  ( rm -f QCLI_I.out QCLI_I.cmd QCLI_I.tmc QCLI_I.log QCLI_I.m; false )

tidy :
	rm -f $(OBJECT)
clean : tidy
	rm -f $(TARGET)
.cvsignore : Makefile
	@for i in $(OBJECT) $(TARGET); do echo "$$i"; done >.cvsignore

CPPFLAGS += -I ../BAT -I ../Inverter
COLFLAGS = -H address.h
address.h : HCIcol.cc
HCIeng.cdf : genui.txt
	genui -d ../eng -c genui.txt
../BAT/BAT_SPAN ../BAT/BS2cdfext ../BAT/BSlogger :
	cd ../BAT && make
../Inverter/Inverter :
	cd ../Inverter && make
../Altimeter/Altimeter :
	cd ../Altimeter && make
BAT_SPAN_cal.tmc : ../BAT/N51AU.txt
	../BAT/BS2tmc.pl ../BAT/N51AU.txt >BAT_SPAN_cal.tmc
ANALDIST = hci_analysis
.PHONY : analdistribution
analdistribution : $(ANALDIST)
	@[ -d $(TGTDIR)/bin/anal ] || mkdir -p $(TGTDIR)/bin/anal
	@distribute $(FORCE) $(TGTDIR)/bin/anal $(ANALDIST)
distribution : analdistribution
