function ui_BATdemo;
f = ne_dialg('Harvard Carbon Isotopes SPAN Demo');
f = ne_dialg(f, 'add', 0, 1, 'gBATdemospan', 'SPAN' );
f = ne_dialg(f, 'add', 1, 0, 'pBATdemospannc', 'NC' );
f = ne_dialg(f, 'add', 1, 0, 'pBATdemospann', 'N' );
f = ne_dialg(f, 'add', 1, 0, 'pBATdemospancpu', 'CPU' );
f = ne_dialg(f, 'add', 1, 0, 'pBATdemospansws', 'SW Stat' );
f = ne_listdirs(f, 'BAT_Data_Dir', 18);
f = ne_dialg(f, 'newcol');
f = ne_dialg(f, 'resize');
