#! /bin/bash
function nl_error {
  echo "getrun: $*" >&2
  exit 1
}

flt=''
gse=hcigse.arp.harvard.edu
relay=fugue.arp.harvard.edu
MM_Dir=MM
CO2_Dir=CO2
RAW_Dir=RAW
use_relay=no
HomeDir=/home/hci
Exp=HCI
RunType=''
Copy_CSV=yes
Copy_CO2=no
Copy_MM=no
Decimate=no
Matlab=yes
SCPOPTS=-Cp

function usage {
  echo "./getrun [options] [axis] [ [runtype] <run> ]+"
  echo " options:"
  echo "   relay: Relay through gateway machine: $relay"
  echo "   nocsv: Don't copy csv files or start matlab"
  echo "   decimate: Retrieve only every 10th scan"
  echo " runtype: flight, cal, data, junk"
  echo "   runtype selection stays in effect until another runtype is selected"
  echo " axis: MM, CO2"
  echo "   axis selections are 'sticky' and apply to all runs"
  exit 0
}

function do_scp {
  RC=''
  [ $use_relay = yes ] && RC="-o 'ProxyCommand /usr/bin/ssh $relay /usr/bin/nc $gse 22'"
  eval time scp $SCPOPTS $RC $*
}

function do_tar {
  # do_tar $run $dir
  # Accesses globals:
  #   use_relay gse relay flt HomeDir RunType Decimate
  run=$1
  src=$2
  PC="ProxyCommand /usr/bin/ssh $relay /usr/bin/nc $gse 22"
  RC=''
  DC=''
  [ $use_relay = yes ] && RC="-o 'ProxyCommand /usr/bin/ssh $relay /usr/bin/nc $gse 22'"
  [ $Decimate = yes ] && DC='--exclude="*[1-9].dat"'
  echo Retrieving $HomeDir/raw/$RunType/$run/$src
  eval time ssh $RC $gse tar -czf- -C $HomeDir/raw/$RunType/$run $DC $src | tar -C $RAW_Dir/$run$flt -xzf-
}

for run in $*; do
  case $run in
    -f) flt=F; RunType=flight;;
    nocsv) Copy_CSV=no;;
    [Cc][Oo]2) Copy_CO2=yes;;
    [Mm][Mm]) Copy_MM=yes;;
    relay) use_relay=yes;;
    decimate) Decimate=yes;;
    nomatlab) Matlab=no;;
    help) usage;;
    --help) usage;;
    cal) flt=''; RunType=cal;;
    flight) flt=F; RunType=flight;;
    data) flt=''; RunType=data;;
    junk) flt=''; RunType=junk;;
    [1-9][0-9][0-9][0-9][0-9][0-9].[0-9]*)
      echo $run
      [ $Copy_CO2 = yes -o $Copy_MM = yes ] && [ -z "$RunType" ] &&
        nl_error "Cannot retrieve CO2 or MM scans without RunType (cal/flight/data/junk)"
      [ -d $RAW_Dir/$run$flt ] || mkdir RAW/$run$flt
      if [ $Copy_CSV = yes ]; then
        [ $Matlab = yes -a ! -f startup.m ] &&
          nl_error "startup.m is missing: copy from HCI eng or select nomatlab"
        do_scp $gse:$HomeDir/anal/$run/*.csv $RAW_Dir/$run$flt
        [ $Matlab = yes ] && echo "$RAW_Dir/$run$flt" >>runs.dat
      fi
      if [ -n "$RunType" ]; then
        [ -f $RAW_Dir/$run$flt/$Exp.log ] ||
          do_scp $gse:$HomeDir/raw/$RunType/$run/$Exp.log $RAW_Dir/$run$flt/$Exp.log
        [ -f $RAW_Dir/$run$flt/saverun.log ] ||
          do_scp $gse:$HomeDir/raw/$RunType/$run/saverun.log $RAW_Dir/$run$flt/saverun.log
      fi;;
    *) nl_error "Unrecognized option: '$run'";;
  esac
done

[ -f runs.dat ] && matlab
for run in $*; do
  case $run in
    -f) :;;
    [Cc][Oo]2) :;;
    [Mm][Mm]) :;;
    relay) :;;
    nocsv) :;;
    decimate) :;;
    nomatlab) :;;
    cal) flt=''; RunType=cal;;
    flight) flt=F; RunType=flight;;
    data) flt=''; RunType=data;;
    junk) flt=''; RunType=junk;;
    *)
      echo $run
      if [ -n "$RunType" ]; then
        [ -f $RAW_Dir/$run$flt/QCLI_C.m ] ||
          do_scp $gse:$HomeDir/raw/$RunType/$run/Base/QCLI_C.m $RAW_Dir/$run$flt/QCLI_C.m
        [ -f $RAW_Dir/$run$flt/QCLI_M.m ] ||
          do_scp $gse:$HomeDir/raw/$RunType/$run/Base/QCLI_M.m $RAW_Dir/$run$flt/QCLI_M.m
        if [ $Copy_CO2 = yes ]; then
          [ -d $CO2_Dir ] || mkdir $CO2_Dir
          [ -d $CO2_Dir/$run$flt ] || mkdir $CO2_Dir/$run$flt
        fi
        if [ $Copy_MM = yes ]; then
          [ -d $MM_Dir ] || mkdir $MM_Dir
          [ -d $MM_Dir/$run$flt ] || mkdir $MM_Dir/$run$flt
        fi
        if [ $Copy_CO2 = yes ]; then
          do_tar $run SSP_C
        fi
        if [ $Copy_MM = yes ]; then
          do_tar $run SSP_M
        fi
      fi
  esac
done
