function pHCIminiminidt_ctrl(varargin);
% pHCIminiminidt_ctrl( [...] );
% MINI Detector T ctrl
h = timeplot({'MDPVCT','MDPVTSt'}, ...
      'MINI Detector T ctrl', ...
      'T ctrl', ...
      {'MDPVCT','MDPVTSt'}, ...
      varargin{:} );
