function pHCIminict_ctrl(varargin);
% pHCIminict_ctrl( [...] );
% MINI Cell T ctrl
h = timeplot({'MCelCT','MCelTSt'}, ...
      'MINI Cell T ctrl', ...
      'T ctrl', ...
      {'MCelCT','MCelTSt'}, ...
      varargin{:} );
