function pHCIisoqclis(varargin);
% pHCIisoqclis( [...] );
% ISO_QCLI Stale
h = timeplot({'QCLI_I_Stale'}, ...
      'ISO_QCLI Stale', ...
      'Stale', ...
      {'QCLI\_I\_Stale'}, ...
      varargin{:} );
