function pHCIminiminisspskipped(varargin);
% pHCIminiminisspskipped( [...] );
% MINI SSP Skipped
h = timeplot({'SSP_M_TS'}, ...
      'MINI SSP Skipped', ...
      'Skipped', ...
      {'SSP\_M\_TS'}, ...
      varargin{:} );
