function pHCIbatspanspanev(varargin);
% pHCIbatspanspanev( [...] );
% SPAN E Vel
h = timeplot({'E_Velocity'}, ...
      'SPAN E Vel', ...
      'E Vel', ...
      {'E\_Velocity'}, ...
      varargin{:} );
