function pHCIcosspstatus(varargin);
% pHCIcosspstatus( [...] );
% CO2 SSP Status
h = timeplot({'SSP_C_Status'}, ...
      'CO2 SSP Status', ...
      'Status', ...
      {'SSP\_C\_Status'}, ...
      varargin{:} );
