function pHCIcosspstale(varargin);
% pHCIcosspstale( [...] );
% CO2_SSP Stale
h = timeplot({'SSP_C_Stale'}, ...
      'CO2_SSP Stale', ...
      'Stale', ...
      {'SSP\_C\_Stale'}, ...
      varargin{:} );
