function pHCIisoisocp(varargin);
% pHCIisoisocp( [...] );
% ISO Cell P
h = timeplot({'ICelHP','ICelLP','ICelP','ICelPSt'}, ...
      'ISO Cell P', ...
      'P', ...
      {'ICelHP','ICelLP','ICelP','ICelPSt'}, ...
      varargin{:} );
