function pHCIisosspt(varargin);
% pHCIisosspt( [...] );
% ISO_SSP Temp
h = timeplot({'I24VT','IPampT','ISSPT','SSP_I_T_FPGA','SSP_I_T_HtSink'}, ...
      'ISO_SSP Temp', ...
      'Temp', ...
      {'I24VT','IPampT','ISSPT','SSP\_I\_T\_FPGA','SSP\_I\_T\_HtSink'}, ...
      varargin{:} );
