function pHCIisotskin(varargin);
% pHCIisotskin( [...] );
% ISO Temps Skin
h = timeplot({'ISk1T','ISk2T','ISk3T'}, ...
      'ISO Temps Skin', ...
      'Skin', ...
      {'ISk1T','ISk2T','ISk3T'}, ...
      varargin{:} );
