function pHCIhkbf(varargin);
% pHCIhkbf( [...] );
% Bubbler Flow
h = timeplot({'Flow1','Flow2','Flow1St','Flow2St'}, ...
      'Bubbler Flow', ...
      'Flow', ...
      {'Flow1','Flow2','Flow1St','Flow2St'}, ...
      varargin{:} );
