function pHCIhk_coolantt(varargin);
% pHCIhk_coolantt( [...] );
% Coolant Temp
h = timeplot({'RadInT','WTnkT','RadOutT'}, ...
      'Coolant Temp', ...
      'Temp', ...
      {'RadInT','WTnkT','RadOutT'}, ...
      varargin{:} );
