function pHCIminits(varargin);
% pHCIminits( [...] );
% MINI Temps Sample
h = timeplot({'MSG1T','MSG2T'}, ...
      'MINI Temps Sample', ...
      'Sample', ...
      {'MSG1T','MSG2T'}, ...
      varargin{:} );
