function pHCIisots(varargin);
% pHCIisots( [...] );
% ISO Temps Sample
h = timeplot({'ISG1T','ISG2T'}, ...
      'ISO Temps Sample', ...
      'Sample', ...
      {'ISG1T','ISG2T'}, ...
      varargin{:} );
