function pHCIhkhs(varargin);
% pHCIhkhs( [...] );
% Hart Stale
h = timeplot({'H0R_Stale','Hart_Stale'}, ...
      'Hart Stale', ...
      'Stale', ...
      {'H0R\_Stale','Hart\_Stale'}, ...
      varargin{:} );
