function pHCIbatspanspanhkinss(varargin);
% pHCIbatspanspanhkinss( [...] );
% SPAN HK INS Status
h = timeplot({'INS_Status'}, ...
      'SPAN HK INS Status', ...
      'INS Status', ...
      {'INS\_Status'}, ...
      varargin{:} );
