function pHCIisoisolc(varargin);
% pHCIisoisolc( [...] );
% ISO Laser Current
h = timeplot({'ILasI'}, ...
      'ISO Laser Current', ...
      'Current', ...
      {'ILasI'}, ...
      varargin{:} );
