function pHCIminiminimlpvt(varargin);
% pHCIminiminimlpvt( [...] );
% MINI MLPV T ctrl
h = timeplot({'MLPVCT','MLPVTSt'}, ...
      'MINI MLPV T ctrl', ...
      'T ctrl', ...
      {'MLPVCT','MLPVTSt'}, ...
      varargin{:} );
