function pHCIhktstatus(varargin);
% pHCIhktstatus( [...] );
% HK Throttle Status
h = ne_dstat({
  'A', 'TVStat', 4; ...
	'B', 'TVStat', 5; ...
	'C', 'TVStat', 7; ...
	'D', 'TVStat', 2; ...
	'I', 'TVStat', 0; ...
	'O', 'TVStat', 1; ...
	'R', 'TVStat', 3; ...
	'Z', 'TVStat', 6 }, 'Status', varargin{:} );
