function pHCIcocqclt(varargin);
% pHCIcocqclt( [...] );
% CO2_CQCL Temp
h = timeplot({'CQCL_T1C','CQCL_T2C'}, ...
      'CO2_CQCL Temp', ...
      'Temp', ...
      {'CQCL\_T1C','CQCL\_T2C'}, ...
      varargin{:} );
