function pHCIco2_co2_qcli_statuss(varargin);
% pHCIco2_co2_qcli_statuss( [...] );
% CO2 QCLI Status Status
h = ne_dstat({
  'CQCLI_Reset_DS', 'DS84C', 1; ...
	'FIFOOvf', 'QCLI_C_CS', 12; ...
	'QCLI_C_Busy', 'QCLI_C_s', 15; ...
	'QCLI_C_cksum', 'QCLI_C_s', 14; ...
	'QCLI_C_cmderr', 'QCLI_C_s', 13; ...
	'QCLI_C_dot', 'QCLI_C_s', 5; ...
	'QCLI_C_InvCmd', 'QCLI_C_s', 11; ...
	'QCLI_C_laser', 'QCLI_C_s', 12; ...
	'QCLI_C_loc', 'QCLI_C_s', 3; ...
	'QCLI_C_lot', 'QCLI_C_s', 4; ...
	'QCLI_C_ready', 'QCLI_C_s', 9; ...
	'QCLI_C_waveerr', 'QCLI_C_s', 8; ...
	'QCLIResponding', 'QCLI_C_CS', 11; ...
	'RBComplete', 'QCLI_C_CS', 9; ...
	'RBPending', 'QCLI_C_CS', 8; ...
	'Reading', 'QCLI_C_CS', 14; ...
	'RWConflict', 'QCLI_C_CS', 13; ...
	'WQPending', 'QCLI_C_CS', 10 }, 'Status', varargin{:} );
