function pHCIhkis(varargin);
% pHCIhkis( [...] );
% Inverter Status
h = ne_dstat({
  'InvCmdS', 'InvQury3', 1; ...
	'InvFailS', 'InvQury2', 2; ...
	'InvFailedS', 'InvQury0', 0; ...
	'InvCmdErrS', 'InvStat', 3; ...
	'InvErrS', 'InvStat', 2; ...
	'InvPwrS', 'InvStat', 1; ...
	'Arm_DS', 'DS84A', 0; ...
	'Arm_S', 'DS873', 0 }, 'Status', varargin{:} );
