function pHCIhk_spacehtt(varargin);
% pHCIhk_spacehtt( [...] );
% HK Space Ht T ctrl
h = timeplot({'SpHCT','SpHtTSt'}, ...
      'HK Space Ht T ctrl', ...
      'T ctrl', ...
      {'SpHCT','SpHtTSt'}, ...
      varargin{:} );
