function pHCIminiminidt(varargin);
% pHCIminiminidt( [...] );
% MINI Detector Temp
h = timeplot({'MDetT'}, ...
      'MINI Detector Temp', ...
      'Temp', ...
      {'MDetT'}, ...
      varargin{:} );
