function pHCIminiqclis(varargin);
% pHCIminiqclis( [...] );
% MINI_QCLI Stale
h = timeplot({'QCLI_M_Stale'}, ...
      'MINI_QCLI Stale', ...
      'Stale', ...
      {'QCLI\_M\_Stale'}, ...
      varargin{:} );
