function pHCIbpss(varargin);
% pHCIbpss( [...] );
% Best Pos Soln Stat
h = timeplot({'SolnStatus'}, ...
      'Best Pos Soln Stat', ...
      'Soln Stat', ...
      {'SolnStatus'}, ...
      varargin{:} );
