function pHCIhkhkcpu(varargin);
% pHCIhkhkcpu( [...] );
% HK HK CPU
h = timeplot({'CPU_Pct','CPU2_Pct'}, ...
      'HK HK CPU', ...
      'CPU', ...
      {'CPU\_Pct','CPU2\_Pct'}, ...
      varargin{:} );
