function pHCIbatspanspannv(varargin);
% pHCIbatspanspannv( [...] );
% SPAN N Vel
h = timeplot({'N_Velocity'}, ...
      'SPAN N Vel', ...
      'N Vel', ...
      {'N\_Velocity'}, ...
      varargin{:} );
