function pHCIbatspanbppt(varargin);
% pHCIbatspanbppt( [...] );
% Best Pos Pos Type
h = timeplot({'PosType'}, ...
      'Best Pos Pos Type', ...
      'Pos Type', ...
      {'PosType'}, ...
      varargin{:} );
