function pHCIminits(varargin);
% pHCIminits( [...] );
% MINI_ Temps Sample
h = timeplot({'MSG1T','MSG2T'}, ...
      'MINI_ Temps Sample', ...
      'Sample', ...
      {'MSG1T','MSG2T'}, ...
      varargin{:} );
