function pHCIbatspanspanhksecs(varargin);
% pHCIbatspanspanhksecs( [...] );
% SPAN HK secs
h = timeplot({'GPS_secs'}, ...
      'SPAN HK secs', ...
      'secs', ...
      {'GPS\_secs'}, ...
      varargin{:} );
