function pHCIminitsspt(varargin);
% pHCIminitsspt( [...] );
% MINI_ Temps SSP_ Temp
h = timeplot({'M24VT','MPampT','MSSPT','SSP_M_T_FPGA','SSP_M_T_HtSink'}, ...
      'MINI_ Temps SSP_ Temp', ...
      'SSP_Temp', ...
      {'M24VT','MPampT','MSSPT','SSP\_M\_T\_FPGA','SSP\_M\_T\_HtSink'}, ...
      varargin{:} );
