function pHCIminidtemp(varargin);
% pHCIminidtemp( [...] );
% MINI_ Detector Temp
h = timeplot({'MDetT'}, ...
      'MINI_ Detector Temp', ...
      'Temp', ...
      {'MDetT'}, ...
      varargin{:} );
