function pHCIbatspanspanl(varargin);
% pHCIbatspanspanl( [...] );
% SPAN Lat
h = timeplot({'Latitude','BP_Lat'}, ...
      'SPAN Lat', ...
      'Lat', ...
      {'Latitude','BP\_Lat'}, ...
      varargin{:} );
