function pHCIisodt(varargin);
% pHCIisodt( [...] );
% ISO_ Detector T_ctrl
h = timeplot({'IDPVCT','IDPVTSt'}, ...
      'ISO_ Detector T_ctrl', ...
      'T_ctrl', ...
      {'IDPVCT','IDPVTSt'}, ...
      varargin{:} );
