function pHCIcotskin(varargin);
% pHCIcotskin( [...] );
% CO2_ Temps Skin
h = timeplot({'CSk1T','CSk2T','CSk3T'}, ...
      'CO2_ Temps Skin', ...
      'Skin', ...
      {'CSk1T','CSk2T','CSk3T'}, ...
      varargin{:} );
