function pHCIminisspw(varargin);
% pHCIminisspw( [...] );
% MINI_SSP Wave
h = timeplot({'QCLI_M_Wave'}, ...
      'MINI_SSP Wave', ...
      'Wave', ...
      {'QCLI\_M\_Wave'}, ...
      varargin{:} );
