function pHCIisoisoqclififo(varargin);
% pHCIisoisoqclififo( [...] );
% ISO QCLI FIFO
h = timeplot({'QCLI_I_fifodep'}, ...
      'ISO QCLI FIFO', ...
      'FIFO', ...
      {'QCLI\_I\_fifodep'}, ...
      varargin{:} );
