function pHCIsparespareai(varargin);
% pHCIsparespareai( [...] );
% SPARE_SPARE AI
h = timeplot({'Sp1AI','Sp2AI','Sp3AI','Sp4AI','Sp5AI','Sp6AI','Sp7AI','Sp8AI','SpAI9'}, ...
      'SPARE_SPARE AI', ...
      'AI', ...
      {'Sp1AI','Sp2AI','Sp3AI','Sp4AI','Sp5AI','Sp6AI','Sp7AI','Sp8AI','SpAI9'}, ...
      varargin{:} );
