function pHCIhkcs(varargin);
% pHCIhkcs( [...] );
% Cal Solenoids
h = ne_dstat({
  '1', 'DS86C', 2; ...
	'2', 'DS86C', 3; ...
	'3', 'DS86C', 4; ...
	'4', 'DS86C', 5; ...
	'5', 'DS86C', 6; ...
	'6', 'DS86C', 7 }, 'Solenoids', varargin{:} );
