function pHCIbprxs(varargin);
% pHCIbprxs( [...] );
% Best Pos RX Stat
h = timeplot({'GPS_Rxvr_Status'}, ...
      'Best Pos RX Stat', ...
      'RX Stat', ...
      {'GPS\_Rxvr\_Status'}, ...
      varargin{:} );
