function pHCIbatspanastale(varargin);
% pHCIbatspanastale( [...] );
% Altimeter Stale
h = timeplot({'MRA_Stale'}, ...
      'Altimeter Stale', ...
      'Stale', ...
      {'MRA\_Stale'}, ...
      varargin{:} );
