function pHCIminiminicp(varargin);
% pHCIminiminicp( [...] );
% MINI Cell P
h = timeplot({'MCelHP','MCelLP','MCelP','MCelPSt'}, ...
      'MINI Cell P', ...
      'P', ...
      {'MCelHP','MCelLP','MCelP','MCelPSt'}, ...
      varargin{:} );
