function pHCIisoisolt(varargin);
% pHCIisoisolt( [...] );
% ISO Laser T ctrl
h = timeplot({'ILTE7R7T','ILTETSt'}, ...
      'ISO Laser T ctrl', ...
      'T ctrl', ...
      {'ILTE7R7T','ILTETSt'}, ...
      varargin{:} );
