function pHCIspanhknr(varargin);
% pHCIspanhknr( [...] );
% SPAN HK N Recs
h = timeplot({'n_span_records','max_span_nc','n_bat_records'}, ...
      'SPAN HK N Recs', ...
      'N Recs', ...
      {'n\_span\_records','max\_span\_nc','n\_bat\_records'}, ...
      varargin{:} );
