function pHCIspanh(varargin);
% pHCIspanh( [...] );
% SPAN Ht
h = timeplot({'Ellipsoidal_Ht','BP_Ht'}, ...
      'SPAN Ht', ...
      'Ht', ...
      {'Ellipsoidal\_Ht','BP\_Ht'}, ...
      varargin{:} );
