function pHCIcoct_ctrl(varargin);
% pHCIcoct_ctrl( [...] );
% CO2 Cell T ctrl
h = timeplot({'CCelCT','CCelTSt'}, ...
      'CO2 Cell T ctrl', ...
      'T_ctrl', ...
      {'CCelCT','CCelTSt'}, ...
      varargin{:} );
