function pHCIbatspanspana(varargin);
% pHCIbatspanspana( [...] );
% SPAN Attitude
h = timeplot({'Roll','Pitch','Azimuth'}, ...
      'SPAN Attitude', ...
      'Attitude', ...
      {'Roll','Pitch','Azimuth'}, ...
      varargin{:} );
