function pHCIsparespareai(varargin);
% pHCIsparespareai( [...] );
% SPARE SPARE AI
h = timeplot({'Sp5AI','Sp6AI','Sp7AI','Sp8AI','SpAI9'}, ...
      'SPARE SPARE AI', ...
      'AI', ...
      {'Sp5AI','Sp6AI','Sp7AI','Sp8AI','SpAI9'}, ...
      varargin{:} );
