function pHCIminiminimlpvtemp(varargin);
% pHCIminiminimlpvtemp( [...] );
% MINI MLPV Temp
h = timeplot({'MLPV_T1C','MLPV_T2C'}, ...
      'MINI MLPV Temp', ...
      'Temp', ...
      {'MLPV\_T1C','MLPV\_T2C'}, ...
      varargin{:} );
