function pHCIspanhki(varargin);
% pHCIspanhki( [...] );
% SPAN HK Idle
h = timeplot({'SPAN_IdleTime'}, ...
      'SPAN HK Idle', ...
      'Idle', ...
      {'SPAN\_IdleTime'}, ...
      varargin{:} );
