function pHCIhksht(varargin);
% pHCIhksht( [...] );
% HK_ Sample Ht T_ctrl
h = timeplot({'SH_CT','SHTSt'}, ...
      'HK_ Sample Ht T_ctrl', ...
      'T_ctrl', ...
      {'SH\_CT','SHTSt'}, ...
      varargin{:} );
