function pHCIminiminimdpvtemp(varargin);
% pHCIminiminimdpvtemp( [...] );
% MINI MDPV Temp
h = timeplot({'MDPV_T1C','MDPV_T2C'}, ...
      'MINI MDPV Temp', ...
      'Temp', ...
      {'MDPV\_T1C','MDPV\_T2C'}, ...
      varargin{:} );
