function pHCIminiqclie(varargin);
% pHCIminiqclie( [...] );
% MINI_QCLI Error
h = timeplot({'QCLI_M_err'}, ...
      'MINI_QCLI Error', ...
      'Error', ...
      {'QCLI\_M\_err'}, ...
      varargin{:} );
