function pHCIct(varargin);
% pHCIct( [...] );
% Coolant Temp
h = timeplot({'WPmpT','WTnkT','CoolT'}, ...
      'Coolant Temp', ...
      'Temp', ...
      {'WPmpT','WTnkT','CoolT'}, ...
      varargin{:} );
