function pHCIiq(varargin);
% pHCIiq( [...] );
% Inverter Qury
h = timeplot({'InvQury0','InvQury1','InvQury2','InvQury3','InvQury4','InvQury5','InvQury6','InvQury7'}, ...
      'Inverter Qury', ...
      'Qury', ...
      {'InvQury0','InvQury1','InvQury2','InvQury3','InvQury4','InvQury5','InvQury6','InvQury7'}, ...
      varargin{:} );
