function pHCIbpess(varargin);
% pHCIbpess( [...] );
% Best Pos ES Stat
h = timeplot({'ExtSolnStatus'}, ...
      'Best Pos ES Stat', ...
      'ES Stat', ...
      {'ExtSolnStatus'}, ...
      varargin{:} );
