function pHCIminisspo(varargin);
% pHCIminisspo( [...] );
% MINI_SSP Overflow
h = timeplot({'SSP_M_Flags'}, ...
      'MINI_SSP Overflow', ...
      'Overflow', ...
      {'SSP\_M\_Flags'}, ...
      varargin{:} );
