function pHCIbatspanspanhkstale(varargin);
% pHCIbatspanspanhkstale( [...] );
% SPAN HK stale
h = timeplot({'BSstale'}, ...
      'SPAN HK stale', ...
      'stale', ...
      {'BSstale'}, ...
      varargin{:} );
