function pHCIisosspstale(varargin);
% pHCIisosspstale( [...] );
% ISO_SSP Stale
h = timeplot({'SSP_I_Stale'}, ...
      'ISO_SSP Stale', ...
      'Stale', ...
      {'SSP\_I\_Stale'}, ...
      varargin{:} );
