function pHCIisoisosspstatus(varargin);
% pHCIisoisosspstatus( [...] );
% ISO SSP Status
h = timeplot({'SSP_I_Status'}, ...
      'ISO SSP Status', ...
      'Status', ...
      {'SSP\_I\_Status'}, ...
      varargin{:} );
