function pHCIminicp(varargin);
% pHCIminicp( [...] );
% MINI_ Cell P
h = timeplot({'MCelHP','MCelLP','MCelP','MCelPSt'}, ...
      'MINI_ Cell P', ...
      'P', ...
      {'MCelHP','MCelLP','MCelP','MCelPSt'}, ...
      varargin{:} );
