function pHCIisoqclie(varargin);
% pHCIisoqclie( [...] );
% ISO_QCLI Error
h = timeplot({'QCLI_I_err'}, ...
      'ISO_QCLI Error', ...
      'Error', ...
      {'QCLI\_I\_err'}, ...
      varargin{:} );
