function pHCIisosspstatus(varargin);
% pHCIisosspstatus( [...] );
% ISO_SSP Status
h = timeplot({'SSP_I_Status'}, ...
      'ISO_SSP Status', ...
      'Status', ...
      {'SSP\_I\_Status'}, ...
      varargin{:} );
