function pHCIisoqcliw(varargin);
% pHCIisoqcliw( [...] );
% ISO_QCLI Wave
h = timeplot({'QCLI_I_Wave'}, ...
      'ISO_QCLI Wave', ...
      'Wave', ...
      {'QCLI\_I\_Wave'}, ...
      varargin{:} );
