function pHCIbpundulation(varargin);
% pHCIbpundulation( [...] );
% Best Pos undulation
h = timeplot({'BP_undulation'}, ...
      'Best Pos undulation', ...
      'undulation', ...
      {'BP\_undulation'}, ...
      varargin{:} );
