function pHCIcocolt_ctrl(varargin);
% pHCIcocolt_ctrl( [...] );
% CO2 Laser T ctrl
h = timeplot({'CLTE4R3T','CLTETSt'}, ...
      'CO2 Laser T ctrl', ...
      'T ctrl', ...
      {'CLTE4R3T','CLTETSt'}, ...
      varargin{:} );
