function pHCIhkpc(varargin);
% pHCIhkpc( [...] );
% HK_ Power Current
h = timeplot({'PM0I1','PM0I2'}, ...
      'HK_ Power Current', ...
      'Current', ...
      {'PM0I1','PM0I2'}, ...
      varargin{:} );
