function pHCIhk_coolantp(varargin);
% pHCIhk_coolantp( [...] );
% Coolant Pressure
h = timeplot({'CoolP'}, ...
      'Coolant Pressure', ...
      'Pressure', ...
      {'CoolP'}, ...
      varargin{:} );
