function pHCIminiminict_ctrl(varargin);
% pHCIminiminict_ctrl( [...] );
% MINI Cell T ctrl
h = timeplot({'MCelCT','MCelTSt'}, ...
      'MINI Cell T ctrl', ...
      'T ctrl', ...
      {'MCelCT','MCelTSt'}, ...
      varargin{:} );
