function pHCIminiminilt_ctrl(varargin);
% pHCIminiminilt_ctrl( [...] );
% MINI Laser T ctrl
h = timeplot({'MLPVCT','MLPVTSt','MLTE7R7T','MLTETSt'}, ...
      'MINI Laser T ctrl', ...
      'T ctrl', ...
      {'MLPVCT','MLPVTSt','MLTE7R7T','MLTETSt'}, ...
      varargin{:} );
