function pHCIisoisoilpvtemp(varargin);
% pHCIisoisoilpvtemp( [...] );
% ISO ILPV Temp
h = timeplot({'ILPV_T1C','ILPV_T2C'}, ...
      'ISO ILPV Temp', ...
      'Temp', ...
      {'ILPV\_T1C','ILPV\_T2C'}, ...
      varargin{:} );
