function pHCIcosspo(varargin);
% pHCIcosspo( [...] );
% CO2_SSP Overflow
h = timeplot({'SSP_C_Flags'}, ...
      'CO2_SSP Overflow', ...
      'Overflow', ...
      {'SSP\_C\_Flags'}, ...
      varargin{:} );
