function pHCIisocp(varargin);
% pHCIisocp( [...] );
% ISO_ Cell P
h = timeplot({'ICelHP','ICelLP','ICelP','ICelPSt'}, ...
      'ISO_ Cell P', ...
      'P', ...
      {'ICelHP','ICelLP','ICelP','ICelPSt'}, ...
      varargin{:} );
