function pHCIminiqcliw(varargin);
% pHCIminiqcliw( [...] );
% MINI_QCLI Wave
h = timeplot({'QCLI_M_Wave'}, ...
      'MINI_QCLI Wave', ...
      'Wave', ...
      {'QCLI\_M\_Wave'}, ...
      varargin{:} );
