function pHCIminimlpvt(varargin);
% pHCIminimlpvt( [...] );
% MINI_MLPV Temp
h = timeplot({'MLPV_T1C','MLPV_T2C'}, ...
      'MINI_MLPV Temp', ...
      'Temp', ...
      {'MLPV\_T1C','MLPV\_T2C'}, ...
      varargin{:} );
