function pHCIiq(varargin);
% pHCIiq( [...] );
% Inverter Qury
h = timeplot({'InvQury5','InvQury6','InvQury7'}, ...
      'Inverter Qury', ...
      'Qury', ...
      {'InvQury5','InvQury6','InvQury7'}, ...
      varargin{:} );
