function pHCIminiminisspf(varargin);
% pHCIminiminisspf( [...] );
% MINI SSP Files
h = timeplot({'SSP_M_Num'}, ...
      'MINI SSP Files', ...
      'Files', ...
      {'SSP\_M\_Num'}, ...
      varargin{:} );
