function pHCIbatspanspanhkweek(varargin);
% pHCIbatspanspanhkweek( [...] );
% SPAN HK week
h = timeplot({'GPS_weekl','GPS_week','BP_Week'}, ...
      'SPAN HK week', ...
      'week', ...
      {'GPS\_weekl','GPS\_week','BP\_Week'}, ...
      varargin{:} );
