function pHCIbatspanbatt(varargin);
% pHCIbatspanbatt( [...] );
% BAT T
h = timeplot({'BAT_TBar','BAT_FOTemp'}, ...
      'BAT T', ...
      'T', ...
      {'BAT\_TBar','BAT\_FOTemp'}, ...
      varargin{:} );
