function pHCIlabls(varargin);
% pHCIlabls( [...] );
% LAB Lab Status
h = ne_dstat({
  'L1_DS', 'DS851', 7; ...
	'L1_S', 'DS86A', 7; ...
	'L2_DS', 'DS84A', 0; ...
	'L2_S', 'DS873', 0 }, 'Status', varargin{:} );
