function pHCIbatspanbpsm(varargin);
% pHCIbatspanbpsm( [...] );
% Best Pos Sig Mask
h = timeplot({'SigMask'}, ...
      'Best Pos Sig Mask', ...
      'Sig Mask', ...
      {'SigMask'}, ...
      varargin{:} );
