function pHCIcolt(varargin);
% pHCIcolt( [...] );
% CO2_ Laser T_ctrl
h = timeplot({'CLPVCT','CLPVTSt','CLTE4R3T','CLTETSt'}, ...
      'CO2_ Laser T_ctrl', ...
      'T_ctrl', ...
      {'CLPVCT','CLPVTSt','CLTE4R3T','CLTETSt'}, ...
      varargin{:} );
