function pHCIct(varargin);
% pHCIct( [...] );
% Coolant Temp
h = timeplot({'RadInT','WTnkT','RadOutT'}, ...
      'Coolant Temp', ...
      'Temp', ...
      {'RadInT','WTnkT','RadOutT'}, ...
      varargin{:} );
