function pHCIisots(varargin);
% pHCIisots( [...] );
% ISO_ Temps Sample
h = timeplot({'ISG1T','ISG2T'}, ...
      'ISO_ Temps Sample', ...
      'Sample', ...
      {'ISG1T','ISG2T'}, ...
      varargin{:} );
