function pHCIminisspf(varargin);
% pHCIminisspf( [...] );
% MINI_SSP Files
h = timeplot({'SSP_M_Num'}, ...
      'MINI_SSP Files', ...
      'Files', ...
      {'SSP\_M\_Num'}, ...
      varargin{:} );
