function pHCIbplonstd(varargin);
% pHCIbplonstd( [...] );
% Best Pos Lon Std
h = timeplot({'BP_LonStd'}, ...
      'Best Pos Lon Std', ...
      'Lon Std', ...
      {'BP\_LonStd'}, ...
      varargin{:} );
