function pHCIminidt_ctrl(varargin);
% pHCIminidt_ctrl( [...] );
% MINI Detector T ctrl
h = timeplot({'MDPVCT','MDPVTSt'}, ...
      'MINI Detector T ctrl', ...
      'T_ctrl', ...
      {'MDPVCT','MDPVTSt'}, ...
      varargin{:} );
