function pHCIminilc(varargin);
% pHCIminilc( [...] );
% MINI_ Laser Current
h = timeplot({'MLasI'}, ...
      'MINI_ Laser Current', ...
      'Current', ...
      {'MLasI'}, ...
      varargin{:} );
