function pHCIisoisoiqclt(varargin);
% pHCIisoisoiqclt( [...] );
% ISO IQCL Temp
h = timeplot({'ILH_T','IQCL_T1C','IQCL_T2C'}, ...
      'ISO IQCL Temp', ...
      'Temp', ...
      {'ILH\_T','IQCL\_T1C','IQCL\_T2C'}, ...
      varargin{:} );
