function pHCIisoisocp(varargin);
% pHCIisoisocp( [...] );
% ISO Cell P
h = timeplot({'ICelHP','ICelLP'}, ...
      'ISO Cell P', ...
      'P', ...
      {'ICelHP','ICelLP'}, ...
      varargin{:} );
