function pHCIhkpc(varargin);
% pHCIhkpc( [...] );
% Power Current
h = timeplot({'PM0I1','PM0I2','PM1I1'}, ...
      'Power Current', ...
      'Current', ...
      {'PM0I1','PM0I2','PM1I1'}, ...
      varargin{:} );
