function pHCIisoisols(varargin);
% pHCIisoisols( [...] );
% ISO Laser Status
h = ne_dstat({
  'ILPV_HC_DS', 'DS851', 5; ...
	'ILPV_HC_S', 'DS86A', 5; ...
	'ILTEC_DS', 'DS851', 6; ...
	'ILTEC_S', 'DS86A', 6 }, 'Status', varargin{:} );
