function pHCIcococt_ctrl(varargin);
% pHCIcococt_ctrl( [...] );
% CO2 Cell T ctrl
h = timeplot({'CCelCT','CCelTSt'}, ...
      'CO2 Cell T ctrl', ...
      'T ctrl', ...
      {'CCelCT','CCelTSt'}, ...
      varargin{:} );
