function pHCIhk_spacehtt(varargin);
% pHCIhk_spacehtt( [...] );
% Space Ht T ctrl
h = timeplot({'SpHCT','SpHtTSt'}, ...
      'Space Ht T ctrl', ...
      'T ctrl', ...
      {'SpHCT','SpHtTSt'}, ...
      varargin{:} );
