function pHCIminiminict(varargin);
% pHCIminiminict( [...] );
% MINI Cell Temp
h = timeplot({'MCel1T','MCel2T'}, ...
      'MINI Cell Temp', ...
      'Temp', ...
      {'MCel1T','MCel2T'}, ...
      varargin{:} );
