function pHCIminiqclififo(varargin);
% pHCIminiqclififo( [...] );
% MINI_QCLI FIFO
h = timeplot({'QCLI_M_fifodep'}, ...
      'MINI_QCLI FIFO', ...
      'FIFO', ...
      {'QCLI\_M\_fifodep'}, ...
      varargin{:} );
