function pHCIisotr(varargin);
% pHCIisotr( [...] );
% Temps Roving
h = timeplot({'IRv1T','IRv2T','IRv3T','IRv4T','IRv5T'}, ...
      'Temps Roving', ...
      'Roving', ...
      {'IRv1T','IRv2T','IRv3T','IRv4T','IRv5T'}, ...
      varargin{:} );
