function pHCIcots(varargin);
% pHCIcots( [...] );
% CO2_ Temps Sample
h = timeplot({'CSG1T','CSG2T'}, ...
      'CO2_ Temps Sample', ...
      'Sample', ...
      {'CSG1T','CSG2T'}, ...
      varargin{:} );
