function pHCIisoisosspskipped(varargin);
% pHCIisoisosspskipped( [...] );
% ISO SSP Skipped
h = timeplot({'SSP_I_TS'}, ...
      'ISO SSP Skipped', ...
      'Skipped', ...
      {'SSP\_I\_TS'}, ...
      varargin{:} );
