function pHCIminisspskipped(varargin);
% pHCIminisspskipped( [...] );
% MINI_SSP Skipped
h = timeplot({'SSP_M_TS'}, ...
      'MINI_SSP Skipped', ...
      'Skipped', ...
      {'SSP\_M\_TS'}, ...
      varargin{:} );
