function pHCIminimqclt(varargin);
% pHCIminimqclt( [...] );
% MINI_MQCL Temp
h = timeplot({'MQCL_T1C','MQCL_T2C'}, ...
      'MINI_MQCL Temp', ...
      'Temp', ...
      {'MQCL\_T1C','MQCL\_T2C'}, ...
      varargin{:} );
