function pHCIcotr(varargin);
% pHCIcotr( [...] );
% CO2_ Temps Roving
h = timeplot({'CRv1T','CRv2T','CRv3T','CRv4T','CRv5T'}, ...
      'CO2_ Temps Roving', ...
      'Roving', ...
      {'CRv1T','CRv2T','CRv3T','CRv4T','CRv5T'}, ...
      varargin{:} );
