function pHCIcoqcliw(varargin);
% pHCIcoqcliw( [...] );
% CO2 QCLI Wave
h = timeplot({'QCLI_C_Wave'}, ...
      'CO2 QCLI Wave', ...
      'Wave', ...
      {'QCLI\_C\_Wave'}, ...
      varargin{:} );
