function pHCIbatspanbpn(varargin);
% pHCIbatspanbpn( [...] );
% Best Pos N
h = timeplot({'NSVs','NSVsSol','NGGL1','NGGL1L2','n_bp_records'}, ...
      'Best Pos N', ...
      'N', ...
      {'NSVs','NSVsSol','NGGL1','NGGL1L2','n\_bp\_records'}, ...
      varargin{:} );
