function pHCIhksht(varargin);
% pHCIhksht( [...] );
% Sample Ht T ctrl
h = timeplot({'SH_CT','SHTSt'}, ...
      'Sample Ht T ctrl', ...
      'T ctrl', ...
      {'SH\_CT','SHTSt'}, ...
      varargin{:} );
