function pHCIminiminilt(varargin);
% pHCIminiminilt( [...] );
% MINI Laser T ctrl
h = timeplot({'MLTE7R7T','MLTETSt'}, ...
      'MINI Laser T ctrl', ...
      'T ctrl', ...
      {'MLTE7R7T','MLTETSt'}, ...
      varargin{:} );
