function pHCIisoisossps(varargin);
% pHCIisoisossps( [...] );
% ISO SSP Scans
h = timeplot({'SSP_I_SN'}, ...
      'ISO SSP Scans', ...
      'Scans', ...
      {'SSP\_I\_SN'}, ...
      varargin{:} );
