function pHCIhk_spacehtc(varargin);
% pHCIhk_spacehtc( [...] );
% Space Ht Camera
h = timeplot({'Cam_T'}, ...
      'Space Ht Camera', ...
      'Camera', ...
      {'Cam\_T'}, ...
      varargin{:} );
