function pHCIcosspskipped(varargin);
% pHCIcosspskipped( [...] );
% CO2_SSP Skipped
h = timeplot({'SSP_C_TS'}, ...
      'CO2_SSP Skipped', ...
      'Skipped', ...
      {'SSP\_C\_TS'}, ...
      varargin{:} );
