function pHCIhk_spacehtt(varargin);
% pHCIhk_spacehtt( [...] );
% HK_ Space Ht T_ctrl
h = timeplot({'SpHCT','SpHtTSt'}, ...
      'HK_ Space Ht T_ctrl', ...
      'T_ctrl', ...
      {'SpHCT','SpHtTSt'}, ...
      varargin{:} );
