function pHCIhkps(varargin);
% pHCIhkps( [...] );
% HK_ Power Status
h = ne_dstat({
  'PM0I1_S', 'PM0Stat', 0; ...
	'PM0I2_S', 'PM0Stat', 2; ...
	'PM0TO_S', 'PM0Stat', 4; ...
	'PM0V1_S', 'PM0Stat', 1; ...
	'PM0V2_S', 'PM0Stat', 3; ...
	'PM1I1_S', 'PM0Stat', 0; ...
	'PM1I2_S', 'PM0Stat', 2; ...
	'PM1TO_S', 'PM0Stat', 4 }, 'Status', varargin{:} );
