function pHCIcocots(varargin);
% pHCIcocots( [...] );
% CO2 Temps Sample
h = timeplot({'CSG1T','CSG2T'}, ...
      'CO2 Temps Sample', ...
      'Sample', ...
      {'CSG1T','CSG2T'}, ...
      varargin{:} );
