function pHCIis(varargin);
% pHCIis( [...] );
% Inverter Status
h = ne_dstat({
  'ICmd', 'InvQury3', 1; ...
	'IFail', 'InvQury2', 2; ...
	'IFailed', 'InvQury0', 0; ...
	'DCmdErr', 'InvStat', 3; ...
	'DError', 'InvStat', 2; ...
	'DPower', 'InvStat', 1; ...
	'Arm', 'DS842', 0 }, 'Status', varargin{:} );
