function pHCIminict_ctrl(varargin);
% pHCIminict_ctrl( [...] );
% MINI_ Cell T_ctrl
h = timeplot({'MCelCT','MCelTSt'}, ...
      'MINI_ Cell T_ctrl', ...
      'T_ctrl', ...
      {'MCelCT','MCelTSt'}, ...
      varargin{:} );
