function pHCIisosspskipped(varargin);
% pHCIisosspskipped( [...] );
% ISO_SSP Skipped
h = timeplot({'SSP_I_TS'}, ...
      'ISO_SSP Skipped', ...
      'Skipped', ...
      {'SSP\_I\_TS'}, ...
      varargin{:} );
