function pHCIcoctemp(varargin);
% pHCIcoctemp( [...] );
% CO2_ Cell Temp
h = timeplot({'CCel1T','CCel2T'}, ...
      'CO2_ Cell Temp', ...
      'Temp', ...
      {'CCel1T','CCel2T'}, ...
      varargin{:} );
