function pHCIisolt(varargin);
% pHCIisolt( [...] );
% ISO_ Laser T_ctrl
h = timeplot({'ILPVTSt','ILTE7R7T','ILTETSt'}, ...
      'ISO_ Laser T_ctrl', ...
      'T_ctrl', ...
      {'ILPVTSt','ILTE7R7T','ILTETSt'}, ...
      varargin{:} );
