function pHCIcocp(varargin);
% pHCIcocp( [...] );
% CO2 Cell P
h = timeplot({'CCelHP','CCelLP','CCelP','CCelPSt'}, ...
      'CO2 Cell P', ...
      'P', ...
      {'CCelHP','CCelLP','CCelP','CCelPSt'}, ...
      varargin{:} );
