function pHCIisoisodt(varargin);
% pHCIisoisodt( [...] );
% ISO Detector T ctrl
h = timeplot({'IDPVCT','IDPVTSt'}, ...
      'ISO Detector T ctrl', ...
      'T ctrl', ...
      {'IDPVCT','IDPVTSt'}, ...
      varargin{:} );
