function pHCIminisspstale(varargin);
% pHCIminisspstale( [...] );
% MINI_SSP Stale
h = timeplot({'SSP_M_Stale'}, ...
      'MINI_SSP Stale', ...
      'Stale', ...
      {'SSP\_M\_Stale'}, ...
      varargin{:} );
