function pHCIcocosspw(varargin);
% pHCIcocosspw( [...] );
% CO2 SSP Wave
h = timeplot({'QCLI_C_Wave'}, ...
      'CO2 SSP Wave', ...
      'Wave', ...
      {'QCLI\_C\_Wave'}, ...
      varargin{:} );
