function pHCIcoqclie(varargin);
% pHCIcoqclie( [...] );
% CO2_QCLI Error
h = timeplot({'QCLI_C_err'}, ...
      'CO2_QCLI Error', ...
      'Error', ...
      {'QCLI\_C\_err'}, ...
      varargin{:} );
