function pHCIcoclpvt(varargin);
% pHCIcoclpvt( [...] );
% CO2 CLPV Temp
h = timeplot({'CLPV_T1C','CLPV_T2C'}, ...
      'CO2 CLPV Temp', ...
      'Temp', ...
      {'CLPV\_T1C','CLPV\_T2C'}, ...
      varargin{:} );
