function pHCIminiminisspstatus(varargin);
% pHCIminiminisspstatus( [...] );
% MINI SSP Status
h = timeplot({'SSP_M_Status'}, ...
      'MINI SSP Status', ...
      'Status', ...
      {'SSP\_M\_Status'}, ...
      varargin{:} );
