function pHCIisoisodpvt(varargin);
% pHCIisoisodpvt( [...] );
% ISO DPV T ctrl
h = timeplot({'IDPVCT','IDPVTSt'}, ...
      'ISO DPV T ctrl', ...
      'T ctrl', ...
      {'IDPVCT','IDPVTSt'}, ...
      varargin{:} );
