function pHCIisoisoctemp(varargin);
% pHCIisoisoctemp( [...] );
% ISO Cell Temp
h = timeplot({'ICel1T','ICel2T','ICelCT','ISk1T','ISk2T','ISk3T'}, ...
      'ISO Cell Temp', ...
      'Temp', ...
      {'ICel1T','ICel2T','ICelCT','ISk1T','ISk2T','ISk3T'}, ...
      varargin{:} );
