function pHCIminiminilc(varargin);
% pHCIminiminilc( [...] );
% MINI Laser Current
h = timeplot({'MLasI'}, ...
      'MINI Laser Current', ...
      'Current', ...
      {'MLasI'}, ...
      varargin{:} );
