function pHCIminitskin(varargin);
% pHCIminitskin( [...] );
% MINI_ Temps Skin
h = timeplot({'MSk1T','MSk2T','MSk3T'}, ...
      'MINI_ Temps Skin', ...
      'Skin', ...
      {'MSk1T','MSk2T','MSk3T'}, ...
      varargin{:} );
