function pHCIminiqclififo(varargin);
% pHCIminiqclififo( [...] );
% MINI QCLI FIFO
h = timeplot({'QCLI_M_fifodep'}, ...
      'MINI QCLI FIFO', ...
      'FIFO', ...
      {'QCLI\_M\_fifodep'}, ...
      varargin{:} );
