function pHCIbatspanbata(varargin);
% pHCIbatspanbata( [...] );
% BAT A
h = timeplot({'BAT_Ax','BAT_Ay','BAT_Az','BAT_Axb','BAT_Ayb','BAT_Azb'}, ...
      'BAT A', ...
      'A', ...
      {'BAT\_Ax','BAT\_Ay','BAT\_Az','BAT\_Axb','BAT\_Ayb','BAT\_Azb'}, ...
      varargin{:} );
