function pHCIbatspanspanuv(varargin);
% pHCIbatspanspanuv( [...] );
% SPAN Up Vel
h = timeplot({'Up_Velocity'}, ...
      'SPAN Up Vel', ...
      'Up Vel', ...
      {'Up\_Velocity'}, ...
      varargin{:} );
