function pHCIhkspareai(varargin);
% pHCIhkspareai( [...] );
% SPARE AI
h = timeplot({'Sp5AI','Sp6AI','Sp7AI','Sp8AI','SpAI9','AIC48','AICD4','AICD6'}, ...
      'SPARE AI', ...
      'AI', ...
      {'Sp5AI','Sp6AI','Sp7AI','Sp8AI','SpAI9','AIC48','AICD4','AICD6'}, ...
      varargin{:} );
