function pHCIcoqclis(varargin);
% pHCIcoqclis( [...] );
% CO2_QCLI Stale
h = timeplot({'QCLI_C_Stale'}, ...
      'CO2_QCLI Stale', ...
      'Stale', ...
      {'QCLI\_C\_Stale'}, ...
      varargin{:} );
