function pHCIisoisoqcliw(varargin);
% pHCIisoisoqcliw( [...] );
% ISO QCLI Wave
h = timeplot({'QCLI_I_Wave'}, ...
      'ISO QCLI Wave', ...
      'Wave', ...
      {'QCLI\_I\_Wave'}, ...
      varargin{:} );
