function pHCIhk_tempss(varargin);
% pHCIhk_tempss( [...] );
% Temps Sample
h = timeplot({'ISG1T','ISG2T'}, ...
      'Temps Sample', ...
      'Sample', ...
      {'ISG1T','ISG2T'}, ...
      varargin{:} );
