function pHCIisoisoqclis(varargin);
% pHCIisoisoqclis( [...] );
% ISO QCLI Stale
h = timeplot({'QCLI_I_Stale'}, ...
      'ISO QCLI Stale', ...
      'Stale', ...
      {'QCLI\_I\_Stale'}, ...
      varargin{:} );
