function pHCIminiminitr(varargin);
% pHCIminiminitr( [...] );
% MINI Temps Roving
h = timeplot({'MRv1T','MRv2T','MRv3T','MRv4T','MRv5T'}, ...
      'MINI Temps Roving', ...
      'Roving', ...
      {'MRv1T','MRv2T','MRv3T','MRv4T','MRv5T'}, ...
      varargin{:} );
