function pHCIminics(varargin);
% pHCIminics( [...] );
% MINI Cell Status
h = ne_dstat({
  'MCell_HC_DS', 'DS868', 2; ...
	'MGas_Ex_Vlv_DS', 'DS84C', 0; ...
	'MGas_Vlv_DS', 'DS868', 7; ...
	'MPrs_Reg_DS', 'DS868', 6 }, 'Status', varargin{:} );
