function pHCIminiminiqcliw(varargin);
% pHCIminiminiqcliw( [...] );
% MINI QCLI Wave
h = timeplot({'QCLI_M_Wave'}, ...
      'MINI QCLI Wave', ...
      'Wave', ...
      {'QCLI\_M\_Wave'}, ...
      varargin{:} );
