function pHCIminiqclis(varargin);
% pHCIminiqclis( [...] );
% MINI QCLI Stale
h = timeplot({'QCLI_M_Stale','SSP_M_Stale'}, ...
      'MINI QCLI Stale', ...
      'Stale', ...
      {'QCLI\_M\_Stale','SSP\_M\_Stale'}, ...
      varargin{:} );
