function pHCIhkdacst(varargin);
% pHCIhkdacst( [...] );
% HK_DACS Temp
h = timeplot({'DACS_T1C','DACS_T2C','PC__T','PS__T','vl_bdT','vl_cpuT'}, ...
      'HK_DACS Temp', ...
      'Temp', ...
      {'DACS\_T1C','DACS\_T2C','PC\_\_T','PS\_\_T','vl\_bdT','vl\_cpuT'}, ...
      varargin{:} );
