function pHCIcocotr(varargin);
% pHCIcocotr( [...] );
% CO2 Temps Roving
h = timeplot({'CRv1T','CRv2T','CRv3T','CRv4T','CRv5T'}, ...
      'CO2 Temps Roving', ...
      'Roving', ...
      {'CRv1T','CRv2T','CRv3T','CRv4T','CRv5T'}, ...
      varargin{:} );
