function pHCIisoiqclt(varargin);
% pHCIisoiqclt( [...] );
% ISO_IQCL Temp
h = timeplot({'IQCL_T1C','IQCL_T2C'}, ...
      'ISO_IQCL Temp', ...
      'Temp', ...
      {'IQCL\_T1C','IQCL\_T2C'}, ...
      varargin{:} );
