function pHCIbpdid(varargin);
% pHCIbpdid( [...] );
% Best Pos Datum ID
h = timeplot({'BP_DatumID'}, ...
      'Best Pos Datum ID', ...
      'Datum ID', ...
      {'BP\_DatumID'}, ...
      varargin{:} );
