function pHCIminissps(varargin);
% pHCIminissps( [...] );
% MINI_SSP Scans
h = timeplot({'SSP_M_SN'}, ...
      'MINI_SSP Scans', ...
      'Scans', ...
      {'SSP\_M\_SN'}, ...
      varargin{:} );
