function pHCIcocoqclififo(varargin);
% pHCIcocoqclififo( [...] );
% CO2 QCLI FIFO
h = timeplot({'QCLI_C_fifodep'}, ...
      'CO2 QCLI FIFO', ...
      'FIFO', ...
      {'QCLI\_C\_fifodep'}, ...
      varargin{:} );
