function pHCIcolt(varargin);
% pHCIcolt( [...] );
% CO2 Laser Temp
h = timeplot({'CLH_T','CQCL_T1C','CQCL_T2C'}, ...
      'CO2 Laser Temp', ...
      'Temp', ...
      {'CLH\_T','CQCL\_T1C','CQCL\_T2C'}, ...
      varargin{:} );
