function pHCIcosspt(varargin);
% pHCIcosspt( [...] );
% CO2_SSP Temp
h = timeplot({'C24VT','CPampT','CSSPT','SSP_C_T_FPGA','SSP_C_T_HtSink'}, ...
      'CO2_SSP Temp', ...
      'Temp', ...
      {'C24VT','CPampT','CSSPT','SSP\_C\_T\_FPGA','SSP\_C\_T\_HtSink'}, ...
      varargin{:} );
