function pHCIminipt(varargin);
% pHCIminipt( [...] );
% MINI_ Pump Temp
h = timeplot({'MPmpT','MPMtT'}, ...
      'MINI_ Pump Temp', ...
      'Temp', ...
      {'MPmpT','MPMtT'}, ...
      varargin{:} );
