function pHCIcocotskin(varargin);
% pHCIcocotskin( [...] );
% CO2 Temps Skin
h = timeplot({'CSk1T','CSk2T','CSk3T'}, ...
      'CO2 Temps Skin', ...
      'Skin', ...
      {'CSk1T','CSk2T','CSk3T'}, ...
      varargin{:} );
