function pHCIminitr(varargin);
% pHCIminitr( [...] );
% MINI_ Temps Roving
h = timeplot({'MRv1T','MRv2T','MRv3T','MRv4T','MRv5T'}, ...
      'MINI_ Temps Roving', ...
      'Roving', ...
      {'MRv1T','MRv2T','MRv3T','MRv4T','MRv5T'}, ...
      varargin{:} );
