function pHCIminiminilrh(varargin);
% pHCIminiminilrh( [...] );
% MINI Laser RH
h = timeplot({'MQCL_RHC'}, ...
      'MINI Laser RH', ...
      'RH', ...
      {'MQCL\_RHC'}, ...
      varargin{:} );
