function pHCIisoisoct(varargin);
% pHCIisoisoct( [...] );
% ISO Cell T ctrl
h = timeplot({'ICelTSt','ICelCT'}, ...
      'ISO Cell T ctrl', ...
      'T ctrl', ...
      {'ICelTSt','ICelCT'}, ...
      varargin{:} );
