function pHCIisoisosspstale(varargin);
% pHCIisoisosspstale( [...] );
% ISO SSP Stale
h = timeplot({'SSP_I_Stale'}, ...
      'ISO SSP Stale', ...
      'Stale', ...
      {'SSP\_I\_Stale'}, ...
      varargin{:} );
