function pHCIbatspanbpls(varargin);
% pHCIbatspanbpls( [...] );
% Best Pos Lat Std
h = timeplot({'BP_LatStd'}, ...
      'Best Pos Lat Std', ...
      'Lat Std', ...
      {'BP\_LatStd'}, ...
      varargin{:} );
