function pHCIhkhs(varargin);
% pHCIhkhs( [...] );
% Hart Stale
h = timeplot({'H1R_Stale','H2R_Stale','Hart_Stale'}, ...
      'Hart Stale', ...
      'Stale', ...
      {'H1R\_Stale','H2R\_Stale','Hart\_Stale'}, ...
      varargin{:} );
