function pHCIcoqclififo(varargin);
% pHCIcoqclififo( [...] );
% CO2_QCLI FIFO
h = timeplot({'QCLI_C_fifodep'}, ...
      'CO2_QCLI FIFO', ...
      'FIFO', ...
      {'QCLI\_C\_fifodep'}, ...
      varargin{:} );
