function pHCIbatspanspanhkts(varargin);
% pHCIbatspanspanhkts( [...] );
% SPAN HK T Stat
h = timeplot({'SPAN_TimeStatus'}, ...
      'SPAN HK T Stat', ...
      'T Stat', ...
      {'SPAN\_TimeStatus'}, ...
      varargin{:} );
