function pHCIminiminilpvt_ctrl(varargin);
% pHCIminiminilt_ctrl( [...] );
% MINI Laser T ctrl
h = timeplot({'MLPVCT','MLPVTSt'}, ...
      'MINI LPV T ctrl', ...
      'T ctrl', ...
      {'MLPVCT','MLPVTSt'}, ...
      varargin{:} );
