function pHCIcolt_ctrl(varargin);
% pHCIcolt_ctrl( [...] );
% CO2 Laser T ctrl
h = timeplot({'CLPVCT','CLPVTSt','CLTE4R3T','CLTETSt'}, ...
      'CO2 Laser T ctrl', ...
      'T ctrl', ...
      {'CLPVCT','CLPVTSt','CLTE4R3T','CLTETSt'}, ...
      varargin{:} );
