function pHCIspanhkmsecs(varargin);
% pHCIspanhkmsecs( [...] );
% SPAN HK msecs
h = timeplot({'GPS_msecs','BP_msecs'}, ...
      'SPAN HK msecs', ...
      'msecs', ...
      {'GPS\_msecs','BP\_msecs'}, ...
      varargin{:} );
