function pHCIisoisodtemp(varargin);
% pHCIisoisodtemp( [...] );
% ISO Detector Temp
h = timeplot({'IDetT'}, ...
      'ISO Detector Temp', ...
      'Temp', ...
      {'IDetT'}, ...
      varargin{:} );
