function pHCIcocosspskipped(varargin);
% pHCIcocosspskipped( [...] );
% CO2 SSP Skipped
h = timeplot({'SSP_C_TS'}, ...
      'CO2 SSP Skipped', ...
      'Skipped', ...
      {'SSP\_C\_TS'}, ...
      varargin{:} );
