function pHCIspanlon(varargin);
% pHCIspanlon( [...] );
% SPAN Lon
h = timeplot({'Longitude','BP_Lon'}, ...
      'SPAN Lon', ...
      'Lon', ...
      {'Longitude','BP\_Lon'}, ...
      varargin{:} );
