function pHCIminisspstatus(varargin);
% pHCIminisspstatus( [...] );
% MINI_SSP Status
h = timeplot({'SSP_M_Status'}, ...
      'MINI_SSP Status', ...
      'Status', ...
      {'SSP\_M\_Status'}, ...
      varargin{:} );
