function pHCIminiminimdpvt(varargin);
% pHCIminiminimdpvt( [...] );
% MINI MDPV T ctrl
h = timeplot({'MDPVCT','MDPVTSt'}, ...
      'MINI MDPV T ctrl', ...
      'T ctrl', ...
      {'MDPVCT','MDPVTSt'}, ...
      varargin{:} );
