function pHCIminisspw(varargin);
% pHCIminisspw( [...] );
% MINI SSP Wave
h = timeplot({'QCLI_M_Wave'}, ...
      'MINI SSP Wave', ...
      'Wave', ...
      {'QCLI\_M\_Wave'}, ...
      varargin{:} );
