function pHCIminiminimdpvrh(varargin);
% pHCIminiminimdpvrh( [...] );
% MINI MDPV RH
h = timeplot({'MDPV_RHC'}, ...
      'MINI MDPV RH', ...
      'RH', ...
      {'MDPV\_RHC'}, ...
      varargin{:} );
