function pHCIisoctemp(varargin);
% pHCIisoctemp( [...] );
% ISO_ Cell Temp
h = timeplot({'ICel1T','ICel2T','ICelCT'}, ...
      'ISO_ Cell Temp', ...
      'Temp', ...
      {'ICel1T','ICel2T','ICelCT'}, ...
      varargin{:} );
