function pHCIcotssp(varargin);
% pHCIcotssp( [...] );
% CO2_ Temps SSP
h = timeplot({'C24VT','CPampT','CSSPT','SSP_C_T_FPGA','SSP_C_T_HtSink'}, ...
      'CO2_ Temps SSP', ...
      'SSP', ...
      {'C24VT','CPampT','CSSPT','SSP\_C\_T\_FPGA','SSP\_C\_T\_HtSink'}, ...
      varargin{:} );
