function pHCIisoisosspt(varargin);
% pHCIisoisosspt( [...] );
% ISO SSP Temp
h = timeplot({'I24VT','IPampT','ISSPT','SSP_I_T_FPGA','SSP_I_T_HtSink'}, ...
      'ISO SSP Temp', ...
      'Temp', ...
      {'I24VT','IPampT','ISSPT','SSP\_I\_T\_FPGA','SSP\_I\_T\_HtSink'}, ...
      varargin{:} );
