function pHCIcocosspf(varargin);
% pHCIcocosspf( [...] );
% CO2 SSP Files
h = timeplot({'SSP_C_Num'}, ...
      'CO2 SSP Files', ...
      'Files', ...
      {'SSP\_C\_Num'}, ...
      varargin{:} );
