function pHCIminict(varargin);
% pHCIminict( [...] );
% MINI_ Cell Temp
h = timeplot({'MCel1T','MCel2T'}, ...
      'MINI_ Cell Temp', ...
      'Temp', ...
      {'MCel1T','MCel2T'}, ...
      varargin{:} );
