function pHCIcoct(varargin);
% pHCIcoct( [...] );
% CO2_ Cell T_ctrl
h = timeplot({'CCelCT','CCelTSt'}, ...
      'CO2_ Cell T_ctrl', ...
      'T_ctrl', ...
      {'CCelCT','CCelTSt'}, ...
      varargin{:} );
